### ISSUE TITLE
Adapter crashed/terminated doing write to a Holding Register

### ISSUE THREAD

**Issue by samot13** [ioBroker/ioBroker.modbus#100]
The modbus adapter terminated during write to a Holding Register

modbus.1 | 2021-03-05 08:34:27.332 | info | (21114) terminating
-- | -- | -- | --
modbus.1 | 2021-03-05 08:34:27.329 | debug | (21114) Closing client on purpose.
modbus.1 | 2021-03-05 08:34:27.325 | silly | (21114) States system redis pmessage  io.messagebox.system.adapter.modbus.1/io.messagebox.system.adapter.modbus.1:{"command":"addNotification","message":{"result":"ok"},"from":"system.host.rock64","ca
modbus.1 | 2021-03-05 08:34:27.291 | error | (21114) Exception-Code: ERR_BUFFER_OUT_OF_BOUNDS: Attempt to access memory outside buffer bounds
modbus.1 | 2021-03-05 08:34:27.291 | error | at Socket.Readable.push (_stream_readable.js:213:10)
modbus.1 | 2021-03-05 08:34:27.291 | error | at readableAddChunk (_stream_readable.js:272:9)
modbus.1 | 2021-03-05 08:34:27.291 | error | at addChunk (_stream_readable.js:297:12)
modbus.1 | 2021-03-05 08:34:27.291 | error | at Socket.emit (events.js:314:20)
modbus.1 | 2021-03-05 08:34:27.291 | error | at Socket.onSocketData (/opt/iobroker/node_modules/iobroker.modbus/lib/jsmodbus/transports/modbus-client-tcp.js:97:26)
modbus.1 | 2021-03-05 08:34:27.291 | error | at Object.emit (/opt/iobroker/node_modules/stampit-event-bus/src/stampit-event-bus.js:20:38)
modbus.1 | 2021-03-05 08:34:27.291 | error | at Object.onData (/opt/iobroker/node_modules/iobroker.modbus/lib/jsmodbus/modbus-client-core.js:111:17)
modbus.1 | 2021-03-05 08:34:27.291 | error | at handleErrorPDU (/opt/iobroker/node_modules/iobroker.modbus/lib/jsmodbus/modbus-client-core.js:73:35)
modbus.1 | 2021-03-05 08:34:27.291 | error | at Buffer.readUInt8 (internal/buffer.js:248:5)
modbus.1 | 2021-03-05 08:34:27.291 | error | at boundsError (internal/buffer.js:80:11)
modbus.1 | 2021-03-05 08:34:27.291 | error | (21114) RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
modbus.1 | 2021-03-05 08:34:27.290 | error | (21114) uncaught exception: Attempt to access memory outside buffer bounds
modbus.1 | 2021-03-05 08:34:27.251 | silly | (21114) States user redis pmessage  modbus.1.*/modbus.1.holdingRegisters.37_Max_Entladestrom  steuern:{"val":100,"ack":false,"ts":1614929667243,"q":0,"from":"system.adapter.admin.0","user":"system.user

Versions:
  - Adapter version: 3.2.4
 - JS-Controller version: 3.2.16
 - Node version: v12.21.0
 - Operating system:  ARMBIAN

**Comment by Apollon77** [comment]
Ok, I can catch that error (comes with next update), but in fact the modbus device sent an invalid answer!
