### ISSUE TITLE
Offset "Alias" not working properly

### ISSUE THREAD

**Issue by JHA-2021** [ioBroker/ioBroker.modbus#101]
**Describe the bug**  

Trying to connect with an Elgris SmartMeter I used the standard setting "Aliases benutzen" which causes on the "Holding Registers" Tab to show a field "Start-Adresse" in the right corner of the window with the Start number "40001".
(According to SunSpec table 203 it should start at 40000, I suppose, btw.)
When I set the addresses of the registers for example 40069 I received "Ilegal Data Address" Error Messages because it tried to poll register 68 instead of 40069.

I guess the "Start address" is supposed to make it easier to insert the first address field? A hint that the holding registers start at address 40000 would be sufficient in my eyes, because after inserting the first address it calculates the next address field anyway (if the next register is needed anyway).

**Versions:**  
 - Adapter version: 3.2.4
 - JS-Controller version: 3.1.6
 - Node version: 12.20.1
 - Operating system: raspberrymatic

![ModBus Adapter](https://user-images.githubusercontent.com/80697380/111287842-e7833a80-8643-11eb-898a-d851ce6439e5.jpg)
![Logfile](https://user-images.githubusercontent.com/80697380/111287973-097cbd00-8644-11eb-9d03-4b8bf5a25147.jpg)

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/121734749-7db8e680-caf5-11eb-8fb7-72b67df3950a.png)

I could not find any documentation, that aliases start from 10000, 20000, 30000
