### ISSUE TITLE
multiple slave addresses 

### ISSUE THREAD

**Issue by nyler84** [ioBroker/ioBroker.modbus#108]
As i know... it is possible to connect to multiple Modbus IDs over RTU.

Is it possible or will it be possible to get data from several TCP devices (different ip addresses) with one adapter. I could imagine that a column would be added to the assignment list for this. In addition to the id, the ip address could also be entered in this column. 

In my case I have to collect data (only two values) from 10 Modbus TCP devices. I think, I currently have to install 10 adapters for this. this would require a lot of memory on my raspberry pi.

**Comment by Apollon77** [comment]
> I think, I currently have to install 10 adapters for this. this would require a lot of memory on my raspberry pi.

Try to run them together in a compact mode group? Feature see https://github.com/ioBroker/ioBroker.js-controller#start-adapter-instances-in-compact-mode , Admin5 and new React UI can also configure that in Admin ... but the adapter needs a last tweak to officially supprot compacr mode ... I could look into this on the weekend if it helps ...
