### ISSUE TITLE
Discrete input not as 1-bit Register

### ISSUE THREAD

**Issue by Lauretana** [ioBroker/ioBroker.modbus#119]
I'm a noob in coding but I would have expected the "discrete inputs" as 1-bit register as described in Wiki

Currently I can select 8/16/32/64 bit register similar to the "input register" and "holding register"
I would expect to be lookalike the "coils"

Could you be so kind to correct me if I'm wrong

**Comment by GermanBluefox** [comment]
This is a GUI bug. Will be fixed as now the GUI will be rewritten with React. During next month.

**Comment by GermanBluefox** [comment]
Fixed
