### ISSUE TITLE
Writing Data in Holding Registers

### ISSUE THREAD

**Issue by mproper23** [ioBroker/ioBroker.modbus#120]
**Describe the bug**  
I have a strange Issue, i can write the register 40003, but im no able to write register 40009, settings are identical. What could be the problem?

this ist the working one:

modbus.0 | 2021-05-19 16:06:20.247 | debug | (2648) Write successfully [2]: 330
-- | -- | -- | --
modbus.0 | 2021-05-19 16:06:20.243 | debug | (2648)  state Changed ack=false:  modbus.0.holdingRegisters.40003_Sollvorlauf_Heizkreis 1:  {"val":33,"ack":false,"ts":1621433180239,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":

and this the fail:

dbus.0 | 2021-05-19 16:05:00.094 | debug | (2648) Poll device 1
-- | -- | -- | --
modbus.0 | 2021-05-19 16:04:59.219 | debug | (2648) Write successfully [8]: 510
modbus.0 | 2021-05-19 16:04:59.205 | debug | (2648) state Changed ack=false:  modbus.0.holdingRegisters.40009_Sollwert_Trinkwasser:  {"val":51,"ack":false,"ts":1621433099202,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":16
modbus.0 | 2021-05-19 16:04:59.028 | debug | (2648) Poll holdingRegs DevID(1) address 0 - 45 bytes

greetings andy

**Versions:**  
 - Adapter version: 3.3.1

**Comment by GermanBluefox** [comment]
And why do think, that second write does not work?

**Comment by Apollon77** [comment]
Please then also ztry upcoming 3.4.0
