### ISSUE TITLE
Weblate no longer working

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.modbus#130]
You seem to have changed something in your adapter which prevents Weblate from working properly.
If you changed anything related to the location of the admin translations, please open an issue here, describing what needs be changed: https://github.com/ioBrokerTranslator/requests/

**Comment by GermanBluefox** [comment]
https://github.com/ioBrokerTranslator/requests/issues/47

**Comment by UncleSamSwiss** [comment]
Updated the path in Weblate.
Thanks for the quick report!
