### ISSUE TITLE
Cannot set parity to "even"

### ISSUE THREAD

**Issue by jmades** [ioBroker/ioBroker.modbus#138]
As a user I want to read a holding register 0x4500 (16Bit) of a "native" modbus device. I configured the iobroker.modbus adapter **not to use aliases** and added a holding register in the following way.
![grafik](https://user-images.githubusercontent.com/65286060/122939015-87eba800-d373-11eb-8b19-df5f613a93b9.png)

The adapter generates:
![grafik](https://user-images.githubusercontent.com/65286060/122951053-452ecd80-d37d-11eb-9531-c2ca10180568.png)

Expected output/request:
01 03 45 00 00 02 Crc1 Crc2

**Comment by GermanBluefox** [comment]
Which version is that?
I cannot reproduce the problem with disabled aliases 
![image](https://user-images.githubusercontent.com/4582016/122976863-22a8ae80-d395-11eb-9eb5-741495f254e5.png)

**Comment by jmades** [comment]
Yes, I installed 3.4.6.
The only difference I recognize is, that I'm using serial communication:
![grafik](https://user-images.githubusercontent.com/65286060/122981550-2c80e080-d39a-11eb-96ec-cfa6fe9d8128.png)

**Comment by jmades** [comment]
Yes, I installed 3.4.6.
The only difference I recognize is, that I'm using serial communication:
![grafik](https://user-images.githubusercontent.com/65286060/122981550-2c80e080-d39a-11eb-96ec-cfa6fe9d8128.png)

**Comment by GermanBluefox** [comment]
What do you see here?
![image](https://user-images.githubusercontent.com/4582016/123110572-83d78d00-d43c-11eb-897b-49128147fed9.png)

**Comment by jmades** [comment]
Where do I find this view/file?

**Comment by jmades** [comment]
Found it, it shows...
![grafik](https://user-images.githubusercontent.com/65286060/123122152-0f095080-d446-11eb-9080-90f8603f1da5.png)

**Comment by jmades** [comment]
I "solved" this issue. The problem belongs to the parity settingsof the serial driver.
Changing the parity from "even" to "none" the device recieves the correct request.

Should I open a new issue for that.

**Comment by Apollon77** [comment]
> Should I open a new issue for that?

What should the adapter do in such a case? SO what would be the issue? In fact you need to make sure to provide correct settings for the connected device ...

**Comment by jmades** [comment]
You got we wrong, or I was not precise enough...again:
Having both, the adapter and the device configured with parity "even" the device receives a wrong request.
Changing both to parity "none" it works. Can you please check if the adpater configures the serial port correctly in case of parity "even".

**Comment by Apollon77** [comment]
Hm ... interesting ... code wise it should be fine. Can you please change config to even and store the settings and then check the "systerm.adapter.modbus.X object JOSN and there in native section what is set there as parity?
YOu can check that in Admin when you enable expert mode and turn off all filters

**Comment by jmades** [comment]
It is even...strange...
![grafik](https://user-images.githubusercontent.com/65286060/123273462-f612a500-d502-11eb-83c2-366a2474dbf5.png)

**Comment by Apollon77** [comment]
Then it should be also used @GermanBluefox  any idea?

**Comment by jmades** [comment]
I did some further testing:
Changed parity in the adapter to "even" and "odd", kept the device parity to "none" --> in both cases I recieve a correct request.
Looks like the serial port is not changing parity.
Adapter runs on a raspberry with an RS485 shield.

Is there a way to check/read back the setting of the serial port

**Comment by GermanBluefox** [comment]
"even" will be delivered to SerialPort.
![image](https://user-images.githubusercontent.com/4582016/123290231-63c5cd80-d511-11eb-94f7-ea0907c9a194.png)

May be it is issue of "serialport" package?

**Comment by Apollon77** [comment]
I yesterday released an update for modbux and also updated serialport ... maybe try again the newest version?

**Comment by jmades** [comment]
Just tested 3.4.8 same behaviour....sorry.
(I'm offline now until Monday - Thanks for your suppport until now, hoping we find the problem.)

**Comment by jmades** [comment]
Back from my trip, I tested the following this morning:
- checked permissions of serial port, but they are ok - set them for test also to 777, without success.
- Changed baudrate instead of parity - this works fine. So there is NO general problem of port settings.

Summary: I still can't change the parity to "even".

**Comment by GermanBluefox** [comment]
We just set the parity in Serialport:
https://github.com/ioBroker/ioBroker.modbus/blob/master/lib/jsmodbus/transports/modbus-client-serial.js#L35

You can verify it yourself by modifying the debug output before new SerialPort to:
`this.log.debug(`connect to serial ${serial.portName} with ${serial.baudRate} and with parity ${serial.parity}`);

And enabling the debug level.

If you see "even" there, so it is issue of Serial port https://github.com/serialport/node-serialport/issues
If you not see "even", it is issue of ioBroker, but it could be fixed very fast and easy.

**Comment by jmades** [comment]
Can you give me a hint how to run (compile) the adapter with the changes mentioned above.
...or is it sufficient to modify the sources here: 
/opt/iobroker/node_modules/iobroker.modbus/lib/jsmodbus/transports
and iobroker compiles the sources before installation of the adpater?

**Comment by GermanBluefox** [comment]
> Can you give me a hint how to run (compile) the adapter with the changes mentioned above.
> ...or is it sufficient to modify the sources here:
> /opt/iobroker/node_modules/iobroker.modbus/lib/jsmodbus/transports
> and iobroker compiles the sources before installation of the adpater?

Just change the code and restart the instance. Nothing must b ecompiled

**Comment by jmades** [comment]
Ok, got it work: ...and I see "even" in the log!
...so it is an issue of Serial port (https://github.com/serialport/node-serialport/issues).
I will open an issue.

**Comment by jmades** [comment]
The problem could be solved by changing the UART (miniUART does not support parity even).
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=198999
