### ISSUE TITLE
Adapter "spams" the ioBroker Log

### ISSUE THREAD

**Issue by Kunibert-007** [ioBroker/ioBroker.modbus#14]
After upgrade to Version 2.03 the Adapter spams messages like this in the ioBroker-Log:

`

modbus.0 | 2018-06-24 00:45:21.878 | debug | Poll holdingRegs DevID(1) address 1500 - 11 bytes
-- | -- | -- | --
modbus.0 | 2018-06-24 00:45:21.871 | debug | Poll inputRegs DevID(1) address 3523 - 25 bytes
modbus.0 | 2018-06-24 00:45:21.867 | debug | Poll inputRegs DevID(1) address 3500 - 6 bytes
modbus.0 | 2018-06-24 00:45:21.862 | debug | Poll inputRegs DevID(1) address 544 - 3 bytes
modbus.0 | 2018-06-24 00:45:21.858 | debug | Poll inputRegs DevID(1) address 506 - 17 bytes

`

The messages are type "debug" but they are logged every second. Before the update to version 2.x there was noch debugging-logging.

**Comment by Apollon77** [comment]
Then change loglevel of this instance to info and you will not see debug logs again. 

Instances -> expert mode -> column loglevel. 

Debug log can be very much depending on the goals of it.
