### ISSUE TITLE
wirenboard module returns "null"

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.modbus#145]
**Describe the bug**  
When connecting the wb-mr 6c v2 module via a usb adapter and specifying the coil registers, the control occurs normally (the relays turn on and off), but the state in the objects is returned null. If poll the same module via modbus poll, there is no such problem.
**To Reproduce**  

**Expected behavior**  
the channel state corresponds to the actual one.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/125462500-c5ff454a-f1ea-4d53-a0eb-a1c1bbf929b2.png)

![image](https://user-images.githubusercontent.com/37106885/125462552-37eb4d83-e136-41ba-ac34-7ddb3305944f.png)

![image](https://user-images.githubusercontent.com/37106885/125462590-3bbee1d6-b7da-4de5-864e-6ac7788124fa.png)

![image](https://user-images.githubusercontent.com/37106885/125462723-a63b4d6c-a39b-450c-9c7b-93a493186566.png)

![image](https://user-images.githubusercontent.com/37106885/125462796-fdae706e-883e-4d65-84fb-79f9c40427a6.png)

![image](https://user-images.githubusercontent.com/37106885/125462871-8dc3fcb3-3203-4f47-891e-e9bcceb328bd.png)

![image](https://user-images.githubusercontent.com/37106885/125462905-350ab45a-c4c9-4610-b9c8-88e3e20bf8bc.png)

**Versions:**  
 - Adapter version: 3.4.9
 - JS-Controller version: 3.3.14
 - Node version: v12.22.1
 - NPM: 6.14.12
 - Operating system: Debian

**Additional context**  
https://wirenboard.com/wiki/Relay_Module_Modbus_Management/en

{
  "_id": "modbus.0.coils.3",
  "type": "state",
  "common": {
    "name": "",
    "role": "switch",
    "type": "boolean",
    "read": false,
    "write": true,
    "def": false
  },
  "native": {
    "regType": "coils",
    "address": 3,
    "deviceId": 152,
    "poll": false,
    "wp": ""
  },
  "from": "system.adapter.modbus.0",
  "user": "system.user.admin",
  "ts": 1626182784988,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by GermanBluefox** [comment]
Включи "Опрос" для значений, которые хочешь видеть

**Comment by Anzic23** [comment]
Вроде включал. В понедельник ещё раз проверю.

**Comment by Anzic23** [comment]
да, если поставить галочку на "опрос", все работает как надо! Спасибо за подсказку!
