### ISSUE TITLE
Last holding register not visible

### ISSUE THREAD

**Issue by dklinger** [ioBroker/ioBroker.modbus#153]
**Describe the bug**  
Add as many holding registeres as necessary until the screen is completely filled.
Then, add another holding register. Try to scroll to the last item. It's not possible as the last item is hidden by the Save-Div.

**To Reproduce**  
1. Go to 'Holding-Register'
2. Click on '+' as many times as needed to fill the whole screen with Entries.
3. Scroll down to 'the last item'
4. See error behavior

**Expected behavior**  
When I scroll down to the botom, the last Entry should be visible and not hidden by the Save-Div.

**Screenshots & Logfiles**  
There is another entry after 375, which is not visible. Scrolling is not possible as the Div Height is not aligned to each other.
![image](https://user-images.githubusercontent.com/2249766/127651348-4faefd00-c1ad-40b9-af9e-4b3fb4c33f26.png)

**Versions:**  
 - Adapter version: 3.4.9
 - JS-Controller version: 3.2.16
 - Node version: 12.22.2
 - Operating system: buanet docker-container

**Comment by Apollon77** [comment]
Which Admin version? 4 or 5?

**Comment by dklinger** [comment]
Admin version is 4.2.2

**Comment by Apollon77** [comment]
Can you please try with Admin 5 (in latest repo)? Because if it is fixed there it will be a "not to be changed". Admin5 will come into stable in next week

**Comment by dklinger** [comment]
Thank, tried with v5 and works well.
Reverted back to v4 and will wait until v5 is stable.

**Comment by Apollon77** [comment]
Thank you for the check! Then I close here :-)
