### ISSUE TITLE
Cron Job zum Abfragen der Daten

### ISSUE THREAD

**Issue by ManuelK83** [ioBroker/ioBroker.modbus#158]
Hallo,

Ist es möglich ein Cronjob in den Adapter zu integrieren. 
Ich benutze aktuell auch noch den sbfspot-Adapter (wo dies einzustellen ist) zum Wechselrichter auslesen.
Das Problem ist nur das die Daten von den beiden Adpatern immer zu unterschiedlichen Zeitpunkten abgefragt werden.  Da ist es schwieriger Berechnungen zu erstellen. 
Habe es vorerst mit einem Script gelöst.

Danke

**Comment by Apollon77** [comment]
Und ein eigenes Skript ist der beste weg. ich denke so eine komplexität muss hier nicht in den Adapter rein.

**Comment by ManuelK83** [comment]
OK schade.
Aber wenn es zu viel Aufwand ist, ist es für mich so OK.
