### ISSUE TITLE
modbus instance doesn't read input register

### ISSUE THREAD

**Issue by derlbear** [ioBroker/ioBroker.modbus#159]
Hi, my modbus instance on a raspberry pi 4 doesn't read all input registers.
The adapter is connected to a systemair ventilation unit.

I entered the input registers and some holding registers...
![input1](https://user-images.githubusercontent.com/60046437/128761922-7001d097-ca62-4af5-a38c-7aa8c9ea41d2.jpg)

... but the modbus instance doesn't pull all of them...
![input3](https://user-images.githubusercontent.com/60046437/128761989-1d49ce3d-afd6-482c-8553-1c03d256a2bd.jpg)

.. so the value stays 0
![input2](https://user-images.githubusercontent.com/60046437/128762038-3341436a-5ccc-42e7-9868-13ccb67c8689.jpg)

When read the input register via qModMaster I receive the right value.

What is my mistake?

**Comment by GermanBluefox** [comment]
Please try the 3.4.12. It was some issue with sorting.

**Comment by derlbear** [comment]
Thank you. That solved my problem.
