### ISSUE TITLE
Object naming issues within HoldingRegisters

### ISSUE THREAD

**Issue by FChristian** [ioBroker/ioBroker.modbus#16]
Naming Convention for objects seems to follow rule ADDRESS_NAME. Like we can see here for example:
![config2](https://user-images.githubusercontent.com/19758651/41824534-ed0a689a-7811-11e8-8496-2ad7255a9007.JPG)

Within the HoldingRegisters, this doesn't seem to work, here it is only NAME:
![config1](https://user-images.githubusercontent.com/19758651/41824533-eceb8c5e-7811-11e8-8dea-9b53bd1dadaf.JPG)

I manually created the 300 new and gave it manually the name ADDRESS_NAME:
![config4](https://user-images.githubusercontent.com/19758651/41824536-ed43df62-7811-11e8-90b7-a72d20e96344.JPG)

This leads to a new object called ADDRES_ADDRESS_NAME:
![config3](https://user-images.githubusercontent.com/19758651/41824535-ed2a9c14-7811-11e8-9bd9-a449f5fd01ed.JPG)

Funny more: EVERY(!) Object within the same instance is renamed to ADDRESS_ADDRESS_NAME:
![config5](https://user-images.githubusercontent.com/19758651/41824537-ed5f41d0-7811-11e8-9336-2a3dd2e4246e.JPG)

Although the instance configuration has not changed (see example here):
![config6](https://user-images.githubusercontent.com/19758651/41824538-ed7ae6ba-7811-11e8-82ac-db1ca0d593b6.JPG)

More Info available here: https://forum.iobroker.net/viewtopic.php?f=20&t=15096&p=157812

**Comment by Apollon77** [comment]
In former modbus versions name was completely free and so up to you ifyou added the ID before or not - but when generating the relas Object-ID the number was always prepending.

SO: you can enter whatever name you want in the name field

**Comment by FChristian** [comment]
Did a full re-install. Now works fine, so this is not really an issue. Thank you!
