### ISSUE TITLE
Issue with HoldingRegisters not in usual address range (with huawei solar inverter)

### ISSUE THREAD

**Issue by tyftle** [ioBroker/ioBroker.modbus#169]
Hi,
Huawei Solar Inverters only accepting function codes 0x03, 0x06 and 0x10. I only want to read holding registers. They usually start at address 40000. But not within the huawei world. They start their registers at 30000. Don't know if this might be a concern.

I tried the connection with QmodMaster and it worked fine with address 32080 in my example.
I do not know, if weather the adapter itself has a problem with the "wrong" address range for the 0x03 holding-register-read command or if the connection is faulty in another way.
Maybe you can clarify, if it's allowed to use 0x03 command for the address-range i would like to receive from.

Working connection with QmodMaster
![Modbus_Settings_Working](https://user-images.githubusercontent.com/90064478/132053643-7e350457-20ad-4968-8cd8-baba7e7f7954.png)

Configuration of modbus adapter
<img width="1357" alt="Bildschirmfoto 2021-09-03 um 20 42 45" src="https://user-images.githubusercontent.com/90064478/132053713-d406b50a-3cde-4e25-9e40-b1e7a9e5081d.png">

<img width="1798" alt="Bildschirmfoto 2021-09-03 um 20 42 14" src="https://user-images.githubusercontent.com/90064478/132053728-6215e12b-ef65-435d-a736-a42a6a4849ce.png">

Error Log
<img width="1279" alt="Bildschirmfoto 2021-09-03 um 20 43 14" src="https://user-images.githubusercontent.com/90064478/132053744-2197f0b2-9f27-4ad0-9d1d-94be9d13df11.png">

Modbus adapter version 3.4.11
js 12.22.1
npm 6.14.12
on raspi

thanks for your time.

**Comment by UwesSmartHome** [comment]
Hi I have the same issue. With QmodMaster I can read correct data. But Modbus adapter has no connection.
