### ISSUE TITLE
Modbus (TCP?) broken with 2.0.4

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/ioBroker.modbus#17]
SInce this update both modbus (TCP) instances stopped working:
`

modbus.0 | 2018-06-26 12:57:40.416 | warn | On error: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":502}
-- | -- | -- | --
modbus.0 | 2018-06-26 12:57:40.416 | error | Client in error state.
modbus.0 | 2018-06-26 12:57:40.414 | error | Socket Error
modbus.1 | 2018-06-26 12:57:29.935 | warn | On error: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":502}
modbus.1 | 2018-06-26 12:57:29.935 | error | Client in error state.
modbus.1 | 2018-06-26 12:57:29.934 | error | Socket Error

`
The addresses 127.0.0.1 are obviously wrong !

**Comment by stabilostick** [comment]
File "modbus-client-tcp.js", line 25 must be
tcp.host = tcp.host || 'localhost';
instead of
tcp.host = tcp.bind || 'localhost';
to fix the IP error.

**Comment by GermanBluefox** [comment]
Thank you.

**Comment by JackWolfskin42** [comment]
Fixed with 2.0.6 !
