### ISSUE TITLE
	(20621) Calculation: eval(value) not possible: ReferenceError: value is not defined

### ISSUE THREAD

**Issue by Rockclimber87** [ioBroker/ioBroker.modbus#170]
Hey Team,

I am reading out my E3DC battery system by modbus.
In the log file I am getting following warn:

<html><body>

  | (20621) Calculation: eval(value) not possible: ReferenceError: value is not defined
-- | --

</body>
</html>

This happens every second few times.
I am a really beginner in the iobroker system so I have no idea where this comes from.
How can I send the log file here?

Thanks for your help in advance.

**Comment by Apollon77** [comment]
Please provide more log. I see two options:

1.) a Modbus formula is used ... then the plaeholder is "x" according to https://github.com/ioBroker/ioBroker.modbus#formula and not "value"
2.) YOu use an Alias with a Calculation function ... then the placeholder is "val" and not "value"

What is it?

**Comment by Rockclimber87** [comment]
How can I provide you more info?
Where can I find the log?

Sorry I am a total newbee...

**Comment by Apollon77** [comment]
The question is if you used a formula or an alias with a formula and used" value" there somewhere?

Else please enable debug log in modbus adapter (Admin - Instances - Expertmode - set Loglevel to "Debug") and post a more detailed log "around" the place when it happens

**Comment by Rockclimber87** [comment]
<html><body>


modbus.0 | 2021-09-06 14:20:17.062 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
-- | -- | -- | --
modbus.0 | 2021-09-06 14:20:17.061 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:17.060 | debug | (27634) Input Value = -1802
modbus.0 | 2021-09-06 14:20:17.051 | debug | (27634) Poll holdingRegs DevID(1) address 75 - 2 bytes
modbus.0 | 2021-09-06 14:20:17.014 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:17.013 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:17.012 | debug | (27634) Input Value = 0
modbus.0 | 2021-09-06 14:20:17.011 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:17.010 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:17.009 | debug | (27634) Input Value = 418
modbus.0 | 2021-09-06 14:20:17.008 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:17.007 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:17.006 | debug | (27634) Input Value = 719
modbus.0 | 2021-09-06 14:20:17.005 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:17.003 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:17.002 | debug | (27634) Input Value = 0
modbus.0 | 2021-09-06 14:20:17.001 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:17.000 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.999 | debug | (27634) Input Value = 202
modbus.0 | 2021-09-06 14:20:16.998 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.997 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.996 | debug | (27634) Input Value = 193
modbus.0 | 2021-09-06 14:20:16.994 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.993 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.992 | debug | (27634) Input Value = 4
modbus.0 | 2021-09-06 14:20:16.991 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.990 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.989 | debug | (27634) Input Value = 2
modbus.0 | 2021-09-06 14:20:16.988 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.986 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.985 | debug | (27634) Input Value = 98
modbus.0 | 2021-09-06 14:20:16.984 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.981 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.980 | debug | (27634) Input Value = 25349
modbus.0 | 2021-09-06 14:20:16.979 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.978 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.977 | debug | (27634) Input Value = -3784
modbus.0 | 2021-09-06 14:20:16.976 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.974 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.973 | debug | (27634) Input Value = 252
modbus.0 | 2021-09-06 14:20:16.971 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.969 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.967 | debug | (27634) Input Value = 0
modbus.0 | 2021-09-06 14:20:16.965 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.963 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.961 | debug | (27634) Input Value = 2234
modbus.0 | 2021-09-06 14:20:16.959 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:16.957 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:16.956 | debug | (27634) Input Value = 258
modbus.0 | 2021-09-06 14:20:16.928 | debug | (27634) Poll holdingRegs DevID(1) address 1 - 100 bytes
modbus.0 | 2021-09-06 14:20:16.924 | debug | (27634) Poll device 1
modbus.0 | 2021-09-06 14:20:01.854 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.851 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.850 | debug | (27634) Input Value = -1810
modbus.0 | 2021-09-06 14:20:01.823 | debug | (27634) Poll holdingRegs DevID(1) address 75 - 2 bytes
modbus.0 | 2021-09-06 14:20:01.780 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.780 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.779 | debug | (27634) Input Value = 0
modbus.0 | 2021-09-06 14:20:01.778 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.778 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.777 | debug | (27634) Input Value = 418
modbus.0 | 2021-09-06 14:20:01.777 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.776 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.775 | debug | (27634) Input Value = 718
modbus.0 | 2021-09-06 14:20:01.775 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.774 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.773 | debug | (27634) Input Value = 0
modbus.0 | 2021-09-06 14:20:01.773 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.772 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.772 | debug | (27634) Input Value = 202
modbus.0 | 2021-09-06 14:20:01.771 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.770 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.770 | debug | (27634) Input Value = 193
modbus.0 | 2021-09-06 14:20:01.769 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.768 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.768 | debug | (27634) Input Value = 4
modbus.0 | 2021-09-06 14:20:01.767 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.767 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.766 | debug | (27634) Input Value = 2
modbus.0 | 2021-09-06 14:20:01.765 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.765 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.764 | debug | (27634) Input Value = 98
modbus.0 | 2021-09-06 14:20:01.763 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.763 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.762 | debug | (27634) Input Value = 25349
modbus.0 | 2021-09-06 14:20:01.761 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.761 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.760 | debug | (27634) Input Value = -3775
modbus.0 | 2021-09-06 14:20:01.760 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.759 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.758 | debug | (27634) Input Value = 267
modbus.0 | 2021-09-06 14:20:01.758 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.757 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.756 | debug | (27634) Input Value = 0
modbus.0 | 2021-09-06 14:20:01.756 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.755 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.754 | debug | (27634) Input Value = 2232
modbus.0 | 2021-09-06 14:20:01.752 | warn | (27634) Calculation: eval(value) not possible: ReferenceError: value is not defined
modbus.0 | 2021-09-06 14:20:01.750 | debug | (27634) Formula = value
modbus.0 | 2021-09-06 14:20:01.749 | debug | (27634) Input Value = 258
modbus.0 | 2021-09-06 14:20:01.717 | debug | (27634) Poll holdingRegs DevID(1) address 1 - 100 bytes
modbus.0 | 2021-09-06 14:20:01.716 | debug | (27634) Initialization of scale factors done!
modbus.0 | 2021-09-06 14:20:01.713 | debug | (27634) Poll device 1
modbus.0 | 2021-09-06 14:20:01.711 | info | (27634) Connected to slave 192.168.10.111
modbus.0 | 2021-09-06 14:20:00.602 | debug | (27634) Add holdingRegisters.40076_Externe_Quelle:  {"_id":"holdingRegisters.40076_Externe_Quelle","type":"state","common":{"name":"Leistung  aller zusätzlichen Einspeiser in Watt","role":"","type":"nu
modbus.0 | 2021-09-06 14:20:00.601 | debug | (27634) Add holdingRegisters.40104_DC_String_3_Power:  {"_id":"holdingRegisters.40104_DC_String_3_Power","type":"state","common":{"name":"Leistung  in Watt","role":"","type":"number","read":false,"writ
modbus.0 | 2021-09-06 14:20:00.600 | debug | (27634) Add holdingRegisters.40103_DC_String_2_Power:  {"_id":"holdingRegisters.40103_DC_String_2_Power","type":"state","common":{"name":"Leistung  in Watt","role":"","type":"number","read":false,"writ
modbus.0 | 2021-09-06 14:20:00.600 | debug | (27634) Add holdingRegisters.40102_DC_String_1_Power:  {"_id":"holdingRegisters.40102_DC_String_1_Power","type":"state","common":{"name":"Leistung  in Watt","role":"","type":"number","read":false,"writ
modbus.0 | 2021-09-06 14:20:00.599 | debug | (27634) Add holdingRegisters.40101_DC_String_3_Current:  {"_id":"holdingRegisters.40101_DC_String_3_Current","type":"state","common":{"name":"Strom  in Ampere","role":"","type":"number","read":true,"wr
modbus.0 | 2021-09-06 14:20:00.598 | debug | (27634) Add holdingRegisters.40100_DC_String_2_Current:  {"_id":"holdingRegisters.40100_DC_String_2_Current","type":"state","common":{"name":"Strom  in Ampere","role":"","type":"number","read":true,"wr
modbus.0 | 2021-09-06 14:20:00.597 | debug | (27634) Add holdingRegisters.40099_DC_String_1_Current:  {"_id":"holdingRegisters.40099_DC_String_1_Current","type":"state","common":{"name":"Strom  in Ampere","role":"","type":"number","read":true,"wr
modbus.0 | 2021-09-06 14:20:00.597 | debug | (27634) Add holdingRegisters.40098_DC_String_3_Voltage:  {"_id":"holdingRegisters.40098_DC_String_3_Voltage","type":"state","common":{"name":"Spannung  in Volt","role":"","type":"number","read":true,"w
modbus.0 | 2021-09-06 14:20:00.596 | debug | (27634) Add holdingRegisters.40097_DC_String_2_Voltage:  {"_id":"holdingRegisters.40097_DC_String_2_Voltage","type":"state","common":{"name":"Spannung  in Volt","role":"","type":"number","read":true,"w
modbus.0 | 2021-09-06 14:20:00.595 | debug | (27634) Add holdingRegisters.40096_DC_String_1_Voltage:  {"_id":"holdingRegisters.40096_DC_String_1_Voltage","type":"state","common":{"name":"Spannung  in Volt","role":"","type":"number","read":true,"w
modbus.0 | 2021-09-06 14:20:00.594 | debug | (27634) Add holdingRegisters.40085_EMS_Status:  {"_id":"holdingRegisters.40085_EMS_Status","type":"state","common":{"name":"EMS-Status","role":"","type":"number","read":true,"write":true,"def":0,"unit
modbus.0 | 2021-09-06 14:20:00.594 | debug | (27634) Add holdingRegisters.40084_Emergency_Power_Status:  {"_id":"holdingRegisters.40084_Emergency_Power_Status","type":"state","common":{"name":"Emergency-Power  Status","role":"","type":"number","r
modbus.0 | 2021-09-06 14:20:00.593 | debug | (27634) Add holdingRegisters.40083_Batterie_SOC:  {"_id":"holdingRegisters.40083_Batterie_SOC","type":"state","common":{"name":"Batterie-SOC  in Prozent","role":"","type":"number","read":true,"write":t
modbus.0 | 2021-09-06 14:20:00.592 | debug | (27634) Add holdingRegisters.40082_Autarkie_Eigenverbrauch:  {"_id":"holdingRegisters.40082_Autarkie_Eigenverbrauch","type":"state","common":{"name":"Autarkie  und Eigenverbrauch","role":"","type":"num
modbus.0 | 2021-09-06 14:20:00.591 | debug | (27634) Add holdingRegisters.40074_Netz_Leistung:  {"_id":"holdingRegisters.40074_Netz_Leistung","type":"state","common":{"name":"Leistung  am Netzübergabepunkt","role":"","type":"number","read":true,"
modbus.0 | 2021-09-06 14:20:00.590 | debug | (27634) Add holdingRegisters.40072_Hausverbrauch_Leistung:  {"_id":"holdingRegisters.40072_Hausverbrauch_Leistung","type":"state","common":{"name":"Hausverbrauchs-Leistung  in Watt","role":"","type":"n
modbus.0 | 2021-09-06 14:20:00.590 | debug | (27634) Add holdingRegisters.40070_Batterie_Leistung:  {"_id":"holdingRegisters.40070_Batterie_Leistung","type":"state","common":{"name":"Batterie-Leistung  in Watt","role":"","type":"number","read":tr
modbus.0 | 2021-09-06 14:20:00.589 | debug | (27634) Add holdingRegisters.40068_PV_Leistung:  {"_id":"holdingRegisters.40068_PV_Leistung","type":"state","common":{"name":"Photovoltaik-Leistung  in Watt","role":"","type":"number","read":true,"writ
modbus.0 | 2021-09-06 14:20:00.588 | debug | (27634) Add holdingRegisters.40052_Firmware:  {"_id":"holdingRegisters.40052_Firmware","type":"state","common":{"name":"Firmware","role":"","type":"string","read":true,"write":true,"def":"","unit":"Re
modbus.0 | 2021-09-06 14:20:00.587 | debug | (27634) Add holdingRegisters.40036_Seriennummer:  {"_id":"holdingRegisters.40036_Seriennummer","type":"state","common":{"name":"Seriennummer","role":"","type":"string","read":true,"write":true,"def":"
modbus.0 | 2021-09-06 14:20:00.587 | debug | (27634) Add holdingRegisters.40020_Modell:  {"_id":"holdingRegisters.40020_Modell","type":"state","common":{"name":"Modell","role":"","type":"string","read":true,"write":true,"def":"","unit":""},"nati
modbus.0 | 2021-09-06 14:20:00.586 | debug | (27634) Add holdingRegisters.40004_Hersteller:  {"_id":"holdingRegisters.40004_Hersteller","type":"state","common":{"name":"Hersteller","role":"","type":"string","read":true,"write":true,"def":"","uni
modbus.0 | 2021-09-06 14:20:00.584 | debug | (27634) Add holdingRegisters.40002_Modbus_Firmware:  {"_id":"holdingRegisters.40002_Modbus_Firmware","type":"state","common":{"name":"Modbus-Firmware-Version","role":"","type":"number","read":true,"wr
modbus.0 | 2021-09-06 14:20:00.583 | debug | (27634) Initialize Objects for holdingRegs:  [{"_address":"40002","name":"Modbus_Firmware","description":"Modbus-Firmware-Version","unit":"","type":"uint16be","len":1,"factor":1,"offset":0,"formula":"
modbus.0 | 2021-09-06 14:20:00.582 | debug | (27634) Initialize Objects for inputRegs: []
modbus.0 | 2021-09-06 14:20:00.581 | debug | (27634) Initialize Objects for coils: []
modbus.0 | 2021-09-06 14:20:00.580 | debug | (27634) Initialize Objects for disInputs: []
modbus.0 | 2021-09-06 14:20:00.262 | info | (27634) starting. Version 3.4.11 in /opt/iobroker/node_modules/iobroker.modbus, node: v12.22.6, js-controller: 3.3.15
modbus.0 | 2021-09-06 14:19:59.851 | debug | (27634) Plugin sentry Initialize Plugin (enabled=true)
modbus.0 | 2021-09-06 14:19:59.427 | debug | (27634) statesDB connected
modbus.0 | 2021-09-06 14:19:59.425 | debug | (27634) States connected to redis: 127.0.0.1:9000
modbus.0 | 2021-09-06 14:19:59.408 | debug | (27634) States create User PubSub Client
modbus.0 | 2021-09-06 14:19:59.404 | debug | (27634) States create System PubSub Client
modbus.0 | 2021-09-06 14:19:59.297 | debug | (27634) Redis States: Use Redis connection: 127.0.0.1:9000
modbus.0 | 2021-09-06 14:19:59.291 | debug | (27634) objectDB connected
modbus.0 | 2021-09-06 14:19:59.273 | debug | (27634) Objects connected to redis: 127.0.0.1:9001
modbus.0 | 2021-09-06 14:19:59.233 | debug | (27634) Objects client initialize lua scripts
modbus.0 | 2021-09-06 14:19:59.231 | debug | (27634) Objects create User PubSub Client
modbus.0 | 2021-09-06 14:19:59.229 | debug | (27634) Objects create System PubSub Client
modbus.0 | 2021-09-06 14:19:59.224 | debug | (27634) Objects client ready ... initialize now
modbus.0 | 2021-09-06 14:19:59.115 | debug | (27634) Redis Objects: Use Redis connection: 127.0.0.1:9001


</body>
</html>

This is the log when turn on the debug loglevel.

**Comment by Apollon77** [comment]
So yes clear you entered "value" in all formula fields ... just remove that from your config and only set a formula when you need it ... and IF then use "x" as the placeholder for the value as staed in documentation

**Comment by Rockclimber87** [comment]
![Screenshot 2021-09-06 142729](https://user-images.githubusercontent.com/89849170/132217451-03bab08f-5e07-4ad2-bb2e-f3d892a5cc90.png)

But there is nothing in formula? isn't it?

**Comment by Apollon77** [comment]
Enable expert mode please (that "head icon")

**Comment by Apollon77** [comment]
Did you maybe a CSV Improit and the values where there?

**Comment by Rockclimber87** [comment]
Found it, thanks for your quick support also for a non expert. Thanks for your patience.
