### ISSUE TITLE
After upgrading from 2.03 to 2.04 Socket-Error / ECONNREFUSED

### ISSUE THREAD

**Issue by Kunibert-007** [ioBroker/ioBroker.modbus#18]
After upgrading from version 2.03 to 2.04 I get the following errors in the log and the adapter has a yellow status:

modbus.0 | 2018-06-26 21:07:43.881 | warn | On error: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":502}
-- | -- | -- | --
modbus.0 | 2018-06-26 21:07:43.853 | error | Client in error state.
modbus.0 | 2018-06-26 21:07:43.850 | error | Socket Error

**Comment by Kunibert-007** [comment]
Ok, see there is already an open issue, sorry. Close this

**Comment by GermanBluefox** [comment]
Bitte mit 2.0.5 testen

**Comment by Kunibert-007** [comment]
Adapter startet wieder ohne Fehler, danke!
