### ISSUE TITLE
How to read holding registers <100?

### ISSUE THREAD

**Issue by Schmattek** [ioBroker/ioBroker.modbus#181]
I have a Kostal smartmeter and I'm trying to read out some values with the modbus adapter and iobroker.

Unfortunately I only get values if I read out addresses >40000. As mentioned in the PDF here: [klick](https://www.kostal-solar-electric.com/en-gb/products/accessories/smart-energy-meter/-/media/document-library-folder---kse/2020/12/15/14/22/ba_kostal_interface_ksem_de.pdf) there are some registers <100 with values I would like to have.

![RMMS](https://user-images.githubusercontent.com/23741192/137044081-4c52eac9-dd8a-44c9-9e3e-c85c359724f5.JPG)

As you can see in the screenshot reading out register 2 (active power-) works great with RMMS. If I try to read out address 2 with the modbus adapter I get an error and the adapter doesn't start (Poll error count: 1 code: {"errorCode":132,"exceptionCode":2,"message":"ILLEGAL DATA ADDRESS"})

Is it even possible to read out registers with this range <40000 or is there any workaround to get theses data?

**Comment by ykuendig** [comment]
I do the exact same like this:
![image](https://user-images.githubusercontent.com/12490872/140538926-36dd537b-61b7-41bb-bda8-ea4787cc3848.png)

**Comment by ykuendig** [comment]
Sicherheitshalber noch die Einstellungsseite:
![image](https://user-images.githubusercontent.com/12490872/140540847-ea1ca92a-5efb-4a2d-b9cd-59da7826a66f.png)
