### ISSUE TITLE
Serial Modbus Slave

### ISSUE THREAD

**Issue by W0RSCHD** [ioBroker/ioBroker.modbus#182]
I have a USB 2 RS485 Device running with my ioBroker and i connected my Proxon Heating to it. (Serial -> dev/ttyUSB0)
But my Proxon Heatin only supports one Master, which is the Central Panel in the Living Room.
So i couldnt get a connection to it. So i need a feature to use it as a SLAVE to connect to my Heating to read Temperatures etc.
Would be great if that could be implemented..

**Comment by bkunder** [comment]
> My fault, got it working :)

I have the same problem. How do you fixed it? May you share your konfig for IOB and RS485 device? Thx.
