### ISSUE TITLE
Factor Column is missing, 

### ISSUE THREAD

**Issue by UwesSmartHome** [ioBroker/ioBroker.modbus#187]
I have used since more as one year the MODBUS Adapter with no issues. I read some data and used for some values the Factor e.g. 0.01 to have the correct value.

Since more as 3 weeks the Factor and Formula column is gone, I can't see it. But the calculation is correct.

![image](https://user-images.githubusercontent.com/45943079/140062358-9473af86-c38a-44a6-a69f-7a997d969e1e.png)

**Versions:**  
 - Adapter version: 3.4.14 (updated but former version the same issue
 - node -v 12.22.6
 - npm -v 6.14.15

 - Operating system: <Buster>

**Comment by UwesSmartHome** [comment]
The same for input registers

![image](https://user-images.githubusercontent.com/45943079/140062662-3de509d8-d678-4ee3-8edb-e7c58bed4e1f.png)

**Comment by ykuendig** [comment]
yepp -  Factor is missing here too / as well as the Offset Field ;-)

**Comment by Apollon77** [comment]
Did you also tried with enabled "Expert mode"?

**Comment by ykuendig** [comment]
If You are talking ybout the Expert-Mode on Instance-Overview  -> then Yes

**Comment by ykuendig** [comment]
Thanks Apollo:
found the setting:
![image](https://user-images.githubusercontent.com/12490872/140538286-9b786a40-2cd8-491c-8461-0bc4c07cf801.png)
Fields are back.

**Comment by Apollon77** [comment]
This looks like an old admin ... :-))

**Comment by ykuendig** [comment]
5.1.25

**Comment by UwesSmartHome** [comment]
Thanks, correct the fields are back

**Comment by UwesSmartHome** [comment]
issue solved
