### ISSUE TITLE
3.4.16 Fehlermeldung

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.modbus#188]
Heute Morgen mit der 3.4.16 die folgende Fehlermeldung bekommen. Rollback auf 3.4.15 - alles wieder OK.

Ich persönlich kann mit der Meldung und der daraus resultierenden Ursache leider nichts anfangen.

<html>
<body>

modbus.0 | 2021-11-11 08:02:24.779 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
modbus.0 | 2021-11-11 08:02:24.777 | info | terminating
modbus.0 | 2021-11-11 08:02:24.632 | error | Cannot read property 'message' of null
modbus.0 | 2021-11-11 08:02:24.632 | error | TypeError: Cannot read property 'message' of null at Immediate.<anonymous> (C:\iobroker\GLT\node_modules\iobroker.modbus\main.js:316:94) at processImmediate (internal/timers.js:463:21)
modbus.0 | 2021-11-11 08:02:24.631 | error | uncaught exception: Cannot read property 'message' of null
modbus.0 | 2021-11-11 08:02:22.750 | info | starting. Version 3.4.16 in C:/iobroker/GLT/node_modules/iobroker.modbus, node: v14.16.0, js-controller: 3.3.18

</body>
</html>

**Comment by Apollon77** [comment]
3.4.17 auf GitHub, geht gerade als version auf npm raus. Sorry
