### ISSUE TITLE
Export device settings

### ISSUE THREAD

**Issue by huwi** [ioBroker/ioBroker.modbus#191]
Hi.

I whish to export / import device settings to save the work i have done or to migrate the settings to a second identical device.
In my house i use 5 EASTRON Smartmeater an i have to type in the same information for all 5 devices.

Kind Regards, Hubert

**Comment by Apollon77** [comment]
What belongs to "device settings" for you?

**Comment by dolomiti70** [comment]
I have the same problem. I think he means import/export of the register settings. In earlier version there was a button for this.
![Screenshot 2021-11-16 203240](https://user-images.githubusercontent.com/43222765/142053477-4f4b6791-31f4-4c21-819c-bf5ef749efac.png)

**Comment by huwi** [comment]
yes, i mean import/export of the register settings.
Sorry, now i have have found the button also. I'm stupid too ;-)
Thank you very mutch.

**Comment by huwi** [comment]
I close this issue.
