### ISSUE TITLE
Delay before accessing the device

### ISSUE THREAD

**Issue by adavt** [ioBroker/ioBroker.modbus#20]
As modbus devices aren't ideal, this parameter will allow to carry out thinner control at poll of the concrete device.

**Comment by GermanBluefox** [comment]
Between which 2 operations should this delay be built in?
Between connect and first read/write? Or between read cycles?

**Comment by adavt** [comment]
It was so long ago that I wouldn't remember. And decided to completely abandon the use of serial and switch to the use of ethernet gateways and the use of modbus TCP.

**Comment by GermanBluefox** [comment]
Anyway now was added the delay between to read requests.
