### ISSUE TITLE
Verbindung zu Solarmax Solar Umrichter geht nicht

### ISSUE THREAD

**Issue by jh2k19** [ioBroker/ioBroker.modbus#205]
Habe schon etliche unterschiedliche Geräte per Modbus.Adapter an ioB angebunden.
Leider funktioniert das mit einem Solarmax MaxStorrage Ultimate von SolarMax nicht.
Über einen Modbus Scanner Tool kann ich die Datenpunkte problemlos auslesen.
Über den ioB Modus Adapter klappt das trotz aller Bemühungen dieses mal nicht.
Hier mal das Protokoll und die Datenpunkliste.
Könnt ihr mir da bitte helfen?

![Screenshot 2022-01-29 183733](https://user-images.githubusercontent.com/51288287/151671302-cac2d22f-40a1-4f68-839e-7dad8f7a5c5d.png)

![Screenshot 2022-01-29 183853](https://user-images.githubusercontent.com/51288287/151671387-705f0507-77b6-4cb3-ac37-60d311e3619c.png)

![Screenshot 2022-01-29 184012](https://user-images.githubusercontent.com/51288287/151671400-e26dd6ae-1be6-41bc-9015-b394ac516001.png)

![Screenshot 2022-01-29 183156](https://user-images.githubusercontent.com/51288287/151671112-ca89dacf-355c-4556-bdb4-9bd208e1485a.png)

![Screenshot 2022-01-29 183426](https://user-images.githubusercontent.com/51288287/151671181-a2842ef3-fd20-47ff-8df9-5611296b0afd.png)

**Comment by jh2k19** [comment]
Vom vielen herumprobieren kamen auch mal Werte in den Objekten. Aber es funktioniert einfach nicht richtig, da der Adapter ja immer di Connection trennt. Also es scheint nur ein kleines Problem zu sein, da ja mal Werte kommen. Aber warum sich die Connection sofort wieder trennt weis ich einfach nicht. Auf einen SmartMeter+ von SolarMax (hat natürlich eine andere IP) kann ich dagegen problemlos zugreifen und der Adapter beendet sich nicht automatisch. Was ist das nur?

**Comment by jh2k19** [comment]
Wenn ich den Adapter per Cron alle 10 sec. neu starte werden die Werte in die Datenpunkten eingelesen und aktualisiert.

**Comment by Apollon77** [comment]
ALso "socket closed with error" besagt eigentlich eher das die gegenstelle den socket schliesst mit einem Fehler ... nicht der Adapter

**Comment by jh2k19** [comment]
Danke für den Hinweis.
Ich versuche morgen mal SolarMax zu erreichen mit der Hoffnung, dass die den Fehler dann auf ihrer Seite beheben können.
Melde mich dann wieder.

**Comment by jh2k19** [comment]
Ich könnte mir noch vorstellen, dass die den Anschluss am Hauptgerät evtl. nicht durchgehend offen halten, weil gleichzeitig auch andere Geräte  (wie z.B. der zweite Solarumrichter oder das Energie Management Modul) mit dem Hauptgerät komunizieren. Oder ist es wie bei jedem anderen Bus, bei dem alle Geräte jederzeit kommunizieren können?

**Comment by Apollon77** [comment]
Naja das kann ggf gut sein ... an sich hätte ich erwartet das mehrere TCP Verbindungen gehen, aber who knows

**Comment by jh2k19** [comment]
Also von Solarmax selbst gibt es keine Hilfe. Die Komponenten sind so abgestimmt, dass die Daten in deren Webportal verarbeitet werden können. Damit habe der Endkunde ja alles was er an Anzeige und Statistik benötige. Es sei nicht angedacht, dass der Endkunde selbst Daten weiterverarbeiten kann oder soll. Außerdem rennen denen die Kunden die Bude ein. Personal fehlt hinten und vorne. Erreichbarkeit = 0. Echt Traurig. 

By the Way...

Ich habe festgestellt, dass der Adapter am leben bleibt, wenn ich die Pollzeit < 900ms mache.
Es kommen ein paar Daten mit denen ich arbeiten kann.
(Leistungen Dach, Netz, Haus, Seriennummer, Firwarestand)
Allerdings fehlen solche wie z.B. erzeugte Energie in kWh, Ströme, CosPhi, Temp. usw.

Falls noch jemand was konstruktives hat, einfach her damit.
