### ISSUE TITLE
Wrong type in info.connection

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.modbus#228]
The admin log shows this warning at adapter start
`modbus.0 | 2022-04-27 08:56:27.681 | warn | This object will not be created in future versions. Please report this to the developer.
modbus.0 | 2022-04-27 08:56:27.681 | warn | Object modbus.0.info.connection is invalid: Default value has to be type "string" but`

**Comment by Apollon77** [comment]
Which adapter verison? SHould be fixed in current 4.x releases

**Comment by BenAhrdt** [comment]
Adapter Version 4.0.4

**Comment by Apollon77** [comment]
Please execute "iob upload modbus" and start adapter again. Still happening? Which js-controller version?
