### ISSUE TITLE
Nur erstes Leerzeichen wird ersetzt, nachfolgende nicht.

### ISSUE THREAD

**Issue by HansPeterMeier** [ioBroker/ioBroker.modbus#235]
Bei den ID Namen unter Objekte wird das erste Leerzeichen durch einen Unterstrich ersetzt.
Nachfolgende Leerzeichen werden dann nicht mehr ersetzt. Denke es wäre schöner, wenn alle Leerzeichen ersetzt werden, oder keine, falls das anderweitig keine Probleme macht.

![image](https://user-images.githubusercontent.com/32676715/167795736-2d50f81f-4dba-4161-9f0f-60e88aedb442.png)
![image](https://user-images.githubusercontent.com/32676715/167796339-8625bdbf-37c9-4a5a-8f89-ada200be81a8.png)
![image](https://user-images.githubusercontent.com/32676715/167796394-146c8509-6914-43a8-9742-f36f7376151f.png)

 - Adapter version: 4.0.4
 - JS-Controller version: 4.0.23
 - Node version: NODE.JS: V14.19.2
 - Operating system: Debian

**Comment by Apollon77** [comment]
Das würde ich aufheben wenn wir mal wieder nen breaking change brauchen :-) Weil es ist einer .....

**Comment by Apollon77** [comment]
Ok, I prepare the change

**Comment by GermanBluefox** [comment]
Fixed in 5.0.3
