### ISSUE TITLE
Benötige Hilfe bei MODBUS-Verbindung zu Hoymiles Wechselrichter / DTU-PRO

### ISSUE THREAD

**Issue by seebaernd** [ioBroker/ioBroker.modbus#238]
Ich benötige Hilfe bei der Integration über MODBUS einer Microwechselrichters von Hoymiles (HM-1500) und DPU-PRO. Habt ihr einen Tipp für mich, wo ich diese am ehesten bekomme? Und damit gleich bitte um Entschuldigung, dass ich github hier missbrauche.

Ich habe bereits geschafft, die DTU-PRO mit iobroker zu verbinden und kann einzelne Werte zu jedem angeschlossenen Solarpanel lesen. Oder auch den Tagesertrag. Siehe angehängten Screenshot.

Es gelingt mir aber nicht, weitere "benachbarte" Werte auszulesen oder Werte mit mehr als 16 bit sinnvoll zu lesen. Das mag schlicht an mir liegen, weil ich einfach Null Erfahrung mit MODBUS habe. Es gibt aber auch unerklärliche Probleme, die in der Implementierung von Hoymiles liegen könnten.

Meine konkrete Frage daher:
Gibt es ein Forum oder kennt jemand interessierte Menschen mit mehr KnowHow, die mir bei der weiteren Analyse und Umsetzung zwecks Auslesung weiterer Werte aus der DPU-PRO behilflich sein könnten?

![grafik](https://user-images.githubusercontent.com/104657313/169996676-26e60a5b-d8e2-458a-ac50-59e0a3cd5791.png)

**Comment by Apollon77** [comment]
Forum, wäre https://forum.iobroker.net und ja ggf da besser. AM besten aber auch screenshots deiner Konfiguration mit posten
