### ISSUE TITLE
[FR] Do not prefix ID with address

### ISSUE THREAD

**Issue by Sineos** [ioBroker/ioBroker.modbus#24]
Please do not prefix the ID with the register's address. This kind of spoils every naming scheme.
![grafik](https://user-images.githubusercontent.com/4459312/44302607-b7a91480-a32c-11e8-81e1-f9dc4bf56126.png)

**Comment by Apollon77** [comment]
What exactly is the topic?

What problems do this create for you?

**Comment by Sineos** [comment]
Well, mostly a cosmetic problem, e.g. in the influxdb series
