### ISSUE TITLE
Factor and Scale Factor

### ISSUE THREAD

**Issue by stwa2020** [ioBroker/ioBroker.modbus#246]
When Factor is used it's not working anymore in combination with Scale Factor formula.

Register is 40094 and SF is 40096

**Register 40094 is correct when Factor is set to 0.001 to have kWh**
![Factor](https://user-images.githubusercontent.com/66866558/171997714-27ac3a3d-3fd6-45d5-a319-a5c45ff52744.png)

![Factor_2](https://user-images.githubusercontent.com/66866558/171997719-60e32fda-6047-444b-86f3-ca8245d50cc5.png)

**Register 40094 is not correct when Factor is set to 0.001 to have kWh and Formula for SF is used, it looks like the Factor is ignored:**
![SF](https://user-images.githubusercontent.com/66866558/171997740-67b1a73b-b4e2-47bc-aa7f-eb1f0a96e8aa.png)

![SF_2](https://user-images.githubusercontent.com/66866558/171997748-b9d0c4f9-5b31-4f5b-badf-b069231d8c0a.png)

**Comment by Apollon77** [comment]
Exactly ... Formular OR Scaling (aka another internal formula). So if you need a scaling include in your formula

**Comment by Apollon77** [comment]
PS: ALso the README tells exactly this. I now made that part bold
