### ISSUE TITLE
Writing Float to Marker in WAGO-PLC

### ISSUE THREAD

**Issue by dolomiti70** [ioBroker/ioBroker.modbus#25]
If I try to write an Float at Address 12288 (First marker doubleword, %MD0), it causes an error with Admin 3.5.x and Modbus 2.0.7 and the Modbus-Adapter restarts.
Writing Float to the PFC-In-Area works.

With Admin 2.0.9 and Modbus 1.1.1 it works fine.

Forum: https://forum.iobroker.net/viewtopic.php?f=20&t=17127#p180254

**Comment by GermanBluefox** [comment]
Should be fixed with 2.0.9 modbus.
