### ISSUE TITLE
falsche Werte bei Phasenleistung

### ISSUE THREAD

**Issue by tis-cs** [ioBroker/ioBroker.modbus#265]
**Describe the bug**  
in den drei Registern für die Phasenleistung wir bei einer Einspeisung durch eine E3/DC S10 E nicht der korrekte Wert angezeigt.
Es sieht so aus, als wenn er bei einem negativen Wert dann 65000 bzgl. des negativen Werts anzeigt, was diese drei Werte somit unbrauchbar macht.

Register:
modbus.0.holdingRegisters.40106_Phasenleistung_in_Watt_L1_L0
modbus.0.holdingRegisters.40107_Phasenleistung_in_Watt_L2_L0
modbus.0.holdingRegisters.40108_Phasenleistung_in_Watt_L3_L0

Beiläufig ist mir aufgefallen, dass der Wert Autarkie ebenfalls falsch darstellt wird (25443%). Dieser müsste aktuell 100% zeigen.

modbus.0.holdingRegisters.40082_Autarkie_Eigenverbrauch

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
<img width="2312" alt="image" src="https://user-images.githubusercontent.com/24519878/192782025-ccfeb560-7945-41bb-a74c-baa3773fb4ba.png">

**Versions:**  
 - Adapter version: 5.0.5
 - JS-Controller version: 4.0.23
 - Node version: <node-version> v16.17.1
 - Operating system: Ubuntu 22.04.1 LTS

**Additional context**

**Comment by Apollon77** [comment]
Hm ... das weisst normalerweise darauf hin das die Register Nummern nicht korrekt sind. Ggf wenn Alias genutzt wird müssen die ggf um eins versetzt angegeben werden (also +1) Bitte mal damit experimentieren.

Sonst brauchen wir bitte die Specs der modbus register, ein Debug Log (inklusive aktiviertem erweiterten debug modus in den settings).

**Comment by tis-cs** [comment]
Ich habe es nun so konfiguriert, sodass ich endlich auf allen drei Phasen korrekte Werte angezeigt bekomme:

**Comment by Apollon77** [comment]
Wenn es für dich tut ist erstmal alles ok - was war jertzt "der Trick"?

**Comment by tis-cs** [comment]
> Wenn es für dich tut ist erstmal alles ok - was war jertzt "der Trick"?

Ich habe den Typ auf "Signed 16 bit (Big Endian)" gestellt. Länge und Faktor jeweils auf "1"

**Comment by Apollon77** [comment]
Also war vorher der falsche Datentyp gewählt und damit wurden die Zahlen falsch interpretiert?

**Comment by tis-cs** [comment]
Ich weiß nicht mehr genau, was default war. Sorry

**Comment by Apollon77** [comment]
Wnn du magst stelle deine einstellungen gern hier zur verfpgung, dann machen andere user vllt nicht den gleichen fehler :-) https://github.com/ioBroker/modbus-templates
