### ISSUE TITLE
Wakeup-Sequenz senden

### ISSUE THREAD

**Issue by tis-cs** [ioBroker/ioBroker.modbus#290]
Ich nutze den Adapter um einen ltron Wärmemengenzähler (Akku) über USB/IR auszulesen.
Ich empfange immer nur dann Daten, wenn ich mit Hilfe von dem mbus-testT Tool (https://github.com/geronet1/mbus-test) mich parallel per Console mit dem selben IR-Kopf verbinde und mit "q" eine Aufwachsequenz sende.
Sonst erhalte ich vom Wärmemengenzähler keine Daten.

Wäre es möglich, dass der modbus Adapter diese Sequenz auch periodisch sendet?

Danke!

**Comment by Apollon77** [comment]
Frage: Bust DU hier richtig? mbus !== modbus??? Müsste das nicht zum mbus Adapter?

**Comment by Apollon77** [comment]
https://github.com/geronet1/mbus-test/blob/main/main.c#L202

**Comment by tis-cs** [comment]
> Frage: Bust DU hier richtig? mbus !== modbus??? Müsste das nicht zum mbus Adapter?

ups, sorry! Vollkommen richtig, war im falschen Kontext und daher auch falscher Adapter :) 
Guten Rutsch!

**Comment by Apollon77** [comment]
Aber gern bei mbus neu anlegen wenn relevant
