### ISSUE TITLE
Neuer Datentyp für Raw-Output möglich?

### ISSUE THREAD

**Issue by octane321** [ioBroker/ioBroker.modbus#315]
Oft muss man mit halbgaren Protokollen arbeiten und weiß nicht welcher Datentyp der richtig ist.

Da wäre ein RAW Datentyp ganz praktisch der den Inhalt unverschleiert offenbart.

 Danke und VG

**Comment by RasputinBerry** [comment]
... ich klinke mich mal ein ...
Ein SMA Wechselrichter verlangt dies hier:
![grafik](https://user-images.githubusercontent.com/56359831/217845958-28e17807-c3ce-4367-805a-67a4925facdd.png)
Wenn man das (oder anderes) eingibt ...
![grafik](https://user-images.githubusercontent.com/56359831/217846231-0947354a-73ec-4109-8064-5867161476c8.png)
.... kommt das als Log:
![grafik](https://user-images.githubusercontent.com/56359831/217846377-e359a55f-8b05-4bdc-be9d-d4a60a4d0d96.png)

**Comment by PLCHome** [comment]
Hi, danke für die Anfrage. 

@octane321 
Ich habe zum Auslesen meiner Wallbox einmal einen RAW Typen implantiert.
Er scheibt die Register angefangen beim 1.le bis zum n.be als hexadezimalen String in das Objekt.
Also 1. Wort 1 und zweites Wort 2 ergäbe bei zwei Wörtern den Text: 00010002

Die Wallbox sendet 5 Bytes mit der Uhrzeit. Mit einem rawstring mit der Größe 5 und der folgenden Formel bekomme ich die Zeitangabe:
`new Date(Date.UTC(parseInt(x.substring(0, 4),16),parseInt(x.substring(4, 8),16)-1,parseInt(x.substring(8, 12),16),parseInt(x.substring(12, 16),16),parseInt(x.substring(16, 20),16))).toLocaleString()`

@RasputinBerry 
Ich habe ebenfalls die Strings überarbeitet. Da war was kaputt. Des Weiteren gibt es wohl Boxen wie meine, die in jedes Wort ein Zeichen und nicht zwei schreibt. Dafür hab ich jetzt auch ein Typen String16 und String16le implementiert.

Wenn ihr das einmaltesten wollt hier ist das Repository:
git@github.com:PLCHome/ioBroker.modbus.git

Ein pull requests ist gestellt. Ich kann aber nicht sagen, wie lange das dauert.

**Comment by octane321** [comment]
Hi @PLCHome,
danke Dir das du dic meldest - das ganze is schon so lange her, das ich gar nicht mehr weiß wozu ich es gebraucht hatte oder wie ich es letztendlich gelöst habe :-D

Aber ich bin mir sicher das es eines Tages nützlich sein wird!

Vielen Dank für deine Mühen
