### ISSUE TITLE
Add possibility to select self named device (udev rule) like Smartmeter Adapter

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.modbus#32]
Please add the possibility to select a self named device (via UDEV rule) like it is handled at Smartmeter Adapter.

**Comment by TbsJah** [comment]
Is the selection by name planned (named via UDEV rule)?
I have connected 2 devices via S0 RS485. 
After each reboot the USB ports are randomly assigned.
It would be very helpful to assign a name here ( similar to Smartmeder Adapter)

**Comment by Apollon77** [comment]
Planned in form of "when someone finds time", yes.

What you can do as workaround is to edit directly the "system.adapter.modbus.X" objects and enter that "by id" path directly there. Only editing adapter settings via admin might be problematic after that

**Comment by TbsJah** [comment]
Thank you very much for your answer (and by the way for your great work)
Just to be sure what we are talking about
Your solution seems to be an easy way to choose the right USB port

![image](https://user-images.githubusercontent.com/34193151/99776848-c2f1d880-2b11-11eb-9407-0b4416442c14.png)

**Comment by Apollon77** [comment]
basically yes ... easier to edit when you use the Raw tab in the dialog of your screenshot

**Comment by TbsJah** [comment]
Thanks a lot!
I can confirm that this workaround works

**Comment by GermanBluefox** [comment]
In 3.4.0 you can enter your port manually
