### ISSUE TITLE
Slave not updating data

### ISSUE THREAD

**Issue by sambaverde** [ioBroker/ioBroker.modbus#34]
Hi
I'm using slave mode and it works fine when entering the data (holding or input register) manual. But if I run a script (blockly or java) updating the data, its not transfered via modbus. in objects vie the data is updated also in attached VIS. It only works if i restart the modbus instance itself. 
Modbus version 2.0.9
Master reading the data is a CMI from Technische Alternative

Idea? Whats the difference entering the register manual to a scripted update?!

**Comment by Lichte12** [comment]
Have you tried to write the data from javascript with ack "false"?
Example: setState('modbus.0.holdingRegisters.12345_Value_01', value, **false**);

This ist working in my application. With ack "true" i had the same issue you described above.
