### ISSUE TITLE
App timeout

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.modbus#341]
Hallo, seit paar Tagen habe ich an einem Client immer mal wieder folgende Warnung:

`<html>
<body>

2023-04-13 18:35:49.294 | warn | Poll error count: 1 code: "App Timeout"
-- | -- | --

</body>
</html>`

Bedeutet "App Timeout" hier, dass der Adapter ein Timeout hat?

**Comment by Apollon77** [comment]
Nein das bedeutet das das Gerät nicht innerhalb der genannten zeit antwortet.
