### ISSUE TITLE
Wertebereichsvorgaben der Objekte berücksichtigen

### ISSUE THREAD

**Issue by Tombra1889** [ioBroker/ioBroker.modbus#342]
Hallo, vom Photovoltaik-Wechselrichter werden in der Nacht negative Werte geschickt, wenn der Wechselrichter sich im Standby befindet. 

In den Objekten habe ich eingestellt, dass der Minimalwert 0 sein soll. Leider warnt der Adapter nur, berücksichtigt dies aber nicht:

`State value to set for "modbus.0.inputRegisters.30961_DC_power_input__2" has value "-2147483648" less than min "0"`

**Comment by Apollon77** [comment]
> In den Objekten habe ich eingestellt, dass der Minimalwert 0 sein soll.

Wie hast Du das getan? Zeige bitte mal Screenshot

**Comment by Tombra1889** [comment]
Hey, ich habe es in den Objekten eingestellt:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/60692414/232306714-ab00acc8-1dd6-47c2-ae60-86fda3305d7a.png">

Leider wird der Wert trotz der Minimaldefinition in das Objekt geschrieben:
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/60692414/232306830-6aa02337-e27c-4b3a-9055-1b80df895999.png">

**Comment by Apollon77** [comment]
Ok, Du hast also das manuell vom Adapter angelegte Objekt angepasst und selbst was reingeschrieben von dem der Adapter nichts weis? Und die Erwartung ist das er das beachtet?

Dann habe ich eine schlechte Nachricht: Der Adapter ist verantwortlich für die angelegten Objekte und es ist ok wenn er von Deinen Änderungen nichts weiss und die daher auch nicht berückhsichtigt. :-)

Es wäre wenn ein Feature Request das der Adapter in den Settings der Modbus Register bestimmte Werte ausfiltern kann, aber das muss anders laufen als so, sorry. Bitte gern feature Request issue anlegen.

Alternativen zum Aussortieren sind kleine JavaScriptchen bzw Alias-Nutzung
