### ISSUE TITLE
Modbus timeout causes connection termination

### ISSUE THREAD

**Issue by mifricke** [ioBroker/ioBroker.modbus#36]
I'm using a Digitus RS485 Converter. This is working fine on Windows using the Tool "QModMaster". 
While the slave is being queried, there is an occasional timeout after some time. The time span is not predictable. In this case QModMaster continues to query and the error is irrelevant for the connection. After the first timeout IoBroker cannot perform a further query until the adapter has been restarted completely. Unfortunately, this is a strange behavior. 
Is this intentional, or is there an error here? From my point of view a single timeout should not cause a connection failure. 

Here is a screenshot of the log output of the Windows tool. The timeout is simply ignored.

<img width="367" alt="bildschirmfoto 2019-01-30 um 18 18 10" src="https://user-images.githubusercontent.com/5204755/52000492-8b89e600-24bd-11e9-8a9c-01de533a000c.png">

Here is a log from ioBroker to illustrate some timeouts.

<img width="1339" alt="bildschirmfoto 2019-01-28 um 16 23 45" src="https://user-images.githubusercontent.com/5204755/52000679-f9cea880-24bd-11e9-815b-874ad06d637f.png">

What triggers "disconnected from slave"? This seems to be triggered by the adapter...

**Comment by darkbrain85** [comment]
#39 

Looks like the same problem...
