### ISSUE TITLE
Modbus not sending ack'ed values

### ISSUE THREAD

**Issue by Sineos** [ioBroker/ioBroker.modbus#42]
I'm observing a strange issue:

- Value are send with an `ioBroker out` node from Node-Red
- When in the Node, the Type is set to `Value` --> Values are shown as `ack = true` in the Objects but never send across the modbus
- When in the Node, the Type is set to `Command` --> Values are shown `as ack = false` in the Objects but are send across the modbus  

https://github.com/ioBroker/ioBroker.modbus/blob/f0fb0b5fe623ce2c0a72a4875c3031ee45ab17a6/main.js#L74
requires the state to be !ack for sending. If I change this line to:
`if (state && id && !infoRegExp.test(id)) {`
the adapter works as expected.

I'm no expert in ioBroker's ack handling, in fact it is quite mysterious to me. Is this behavior intended?

**Comment by Apollon77** [comment]
Yes, this is completely correct. "ack=true" is not meaned to "control" anything ... onky "ack=false" are send to other parties. So make sure to set ack=false if you want values to get send
