### ISSUE TITLE
Einstellungen werden nicht angezeigt

### ISSUE THREAD

**Issue by Forestarius** [ioBroker/ioBroker.modbus#443]
Der Adapter läuft schon lange ohne Probleme

Jedoch habe ich gerade festgestellt, dass ich keine Einstellungen mehr sehe.

Iobroker, gehe auf Instanzen, dann auf Modbusadapter, dort auf Einstellungen und bekomme nichts mehr angezeigt.

![Modbus](https://github.com/ioBroker/ioBroker.modbus/assets/55843266/698e7e39-a09c-45b7-8094-0f971edd113b)

**Comment by Apollon77** [comment]
Is the JavaScritp error console showing any error or logs?

**Comment by Forestarius** [comment]
Wo finde ich die Console? Unter den Punkt Protokoll laufen keine Fehler auf.

**Comment by Apollon77** [comment]
Im Browder meistens Web-Entwickler Tools oder so

**Comment by Forestarius** [comment]
Danke :-) 

Das steht in der Console
![modbus console](https://github.com/ioBroker/ioBroker.modbus/assets/55843266/c87960be-a3c7-4d5e-a5c0-eef99ade9e95)

**Comment by Apollon77** [comment]
Hm ... an nsich nichts relevantes. Komisch. Mach mal ein neues "iob upload modbus"

**Comment by Forestarius** [comment]
Hi, habe die Version 6.0.0 installiert und danach wieder die 6.0.1 drüber und es klappt. Lag dann wohl an meinem System
