### ISSUE TITLE
Wo wird die Instanz Konfiguration gespeichert?

### ISSUE THREAD

**Issue by DodoMoep** [ioBroker/ioBroker.modbus#460]
Hallo zusammen,

ich habe hier einen kaputten iobroker, ebenfalls mit kaputten Backups.
Es ist noch der Zugriff auf das komplette iobroker Verzeichnis möglich.

Kann ich irgendwo aus dem Dateisystem die Konfiguration der Instanzen auslesen?

**Comment by Apollon77** [comment]
Formal sollte das über suchen in der objects.jsonl möglich sein ... dort sollte ein key "system.adapter.modbus.0" existieren mit dem Instanz objekt ... das rausholen und ggf in einer neuen instanz via admin anpassen

**Comment by DodoMoep** [comment]
Hey @Apollon77 

tausend Dank!
Ich habe die Config gefunden :)
