### ISSUE TITLE
Graceful disconnect

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.modbus#48]
My client (Solaredge inverter) regularly runs into a timeout when it is handling other requests. This seems to be normal modbus behaviour (collision detection).
I therefore have modified the flush function modbus-client-core.js like that:

```
                currentRequest.timeout = setTimeout(() => {
                    currentRequest.cb && currentRequest.cb();
                    this.log.warn('Request timed out');
                    this.setState('ready');
                }, this.options.timeout);
```

This way it does not disconnect but simply retries. This gives a much smoother behaviour.

**Comment by Apollon77** [comment]
But should we then not have kind of a counter that make sure that a real reconnect happens when it stays timing out?

**Comment by cburghardt** [comment]
You already have this in pollResult, the error count still works. So after the max number of errors it disconnects and connects again.

In addition I have pimped the modbus to also change the polling interval based upon daylight but that's probably a very specific use case ;)
