### ISSUE TITLE
Problems Import and Export Holding Registers

### ISSUE THREAD

**Issue by odermerk** [ioBroker/ioBroker.modbus#50]
Hey there!
I have a problem by export and import of Holding registers.
If you choose the option use more ID`s, the Slave ID isn´t given or set by import or export.
Also the poll and WP isn´t set when you import data. (See picture)
It was exported and then imported.

![Unbenannt](https://user-images.githubusercontent.com/49350212/60514866-abc30880-9cda-11e9-8b70-895890b98bc0.JPG)

Data:
47	Chalet 1b P-3	Leistung L3	KW	uint32be	2	0.01	0	level		false	false	

Sometimes it helps a lot to create a bigger list external and then import to the modul.
It saves a lot of work, when you don´t have to type everything byself.

Thank you.

Daniel

**Comment by necotec** [comment]
Hello, here is a little workaround.

@odermerk You can create a seperated line with the Slave-ID. you must name the line as "deviceID". Then you can import the IDs. I have attatched a picture of my csv-file.
![iobroker_workaround_modbus_import](https://user-images.githubusercontent.com/34749799/66997312-7ea43580-f0d2-11e9-8351-fee07d647bfc.png)
