### ISSUE TITLE
Warning regarding scale factor after upgrade to 6.2.0

### ISSUE THREAD

**Issue by disaster123** [ioBroker/ioBroker.modbus#500]
**Describe the bug**  

6.1.0 is working fine.

6.2.0 spams the log with:
`
[DevID_3/inputRegs/30781] Calculation of a scaleFactor which is based on another scaleFactor seems strange. Please check the config for address 30781 !

modbus.0
2024-04-12 16:23:48.787	warn	[DevID_3/inputRegs/30779] Calculation of a scaleFactor which is based on another scaleFactor seems strange. Please check the config for address 30779 !
`

**Expected behavior**  

6.2.0 should work as 6.1.0

**Screenshots & Logfiles**  

Config:
![image](https://github.com/ioBroker/ioBroker.modbus/assets/861558/dc384146-b97f-4887-accb-ed5a3a2678c2)

**Comment by Norb1204** [comment]
I see the same behavior with version 6.2.0.

**Comment by Steff42** [comment]
Here the same.
I have several formulas like this one `x*Math.pow(10, sf['40082'])` in my modbus registers and now every one is marked as warning.
In the ioBroker Forum there is a thread
[https://forum.iobroker.net/topic/74076/gel%C3%B6st-warn-nach-update-auf-modbus-6-2-0](url)
with a solution. But this works not for me.
Mayby i have to try other calculations in my formulas.

**Comment by greatfireball** [comment]
Same here... I am using a Solaredge Inverter.

**Comment by tops4u** [comment]
Same here. Using 2x SMA. Part of my Config:

<img width="1257" alt="image" src="https://github.com/ioBroker/ioBroker.modbus/assets/6877067/fb14a519-5a96-4e7e-904f-8afddb71a877">

**Comment by Strobelix80** [comment]
Same here with formular like `x*Math.pow(10, sf['40082'])`

**Comment by PLCHome** [comment]
![image](https://github.com/ioBroker/ioBroker.modbus/assets/29116097/725637f9-1392-4814-b9d6-ed37665f1b1b)

Unfortunately I removed two lines too many.

If you insert the two marked lines the error is gone.
The reason was that I wanted to allow strings as SF. This works alternately. Unfortunately he added all the lines. Unfortunately it failed me during the tests.

I'll do a PR right away. Sorry for that.

Maybe someone else can test whether the error has really gone away for them.

**Comment by PLCHome** [comment]
The corrected version can be found here:
https://github.com/PLCHome/ioBroker.modbus/blob/master/lib/master.js

**Comment by PLCHome** [comment]
@Steff42

> Here the same. I have several formulas like this one `x*Math.pow(10, sf['40082'])` in my modbus registers and now every one is marked as warning. In the ioBroker Forum there is a thread [https://forum.iobroker.net/topic/74076/gel%C3%B6st-warn-nach-update-auf-modbus-6-2-0](url) with a solution. But this works not for me. Mayby i have to try other calculations in my formulas.

If you know where the error comes from, I can understand why it didn't work for you.

**Comment by Steff42** [comment]
@PLCHome,
thank you for your reply, but my Javascript skills are not yet so good that I understand the reason for this.
I try your corrected version.

> Sorry for that.

No problem, we are all human!

Thx Steffen

**Comment by Steff42** [comment]
@PLCHome,
corrected version works fine!

Thx Steffen

**Comment by PLCHome** [comment]
Thanx for testing.

**Comment by tops4u** [comment]
@PLCHome your file works for me. Thanks!

**Comment by Apollon77** [comment]
6.2.1 on it's way

**Comment by Apollon77** [comment]
Thanks @PLCHome  for the fix!
