### ISSUE TITLE
Poll error in case of addresses aligned to 16 Bit

### ISSUE THREAD

**Issue by Q7Jensen** [ioBroker/ioBroker.modbus#509]
Some addresses not polled when aligned to 16Bit.   
(doNotRoundAddressToWord = false)
I'm not sure, if all is described correctly. Over all, if the checkBox isn't checked (default), i have problems, if checked it seems to be ok.

**To Reproduce**  
in case of my address list (see attachment), at least 4 addresses not polled (if not align the addresses to 16 bit is not checked)
(12432 - 12435)

**Expected behavior**  
poll all requested addresses

**Screenshots & Logfiles**  
2024-05-08 18:04:49.341 - [34mdebug[39m: modbus.1 (5752) [DevID_1/coils] Poll address 12288 - 16 bits
2024-05-08 18:04:49.343 - [34mdebug[39m: modbus.1 (5752) [DevID_1/coils] Poll address 12304 - 16 bits
2024-05-08 18:04:49.344 - [34mdebug[39m: modbus.1 (5752) [DevID_1/coils] Poll address 12320 - 64 bits
2024-05-08 18:04:49.345 - [34mdebug[39m: modbus.1 (5752) [DevID_1/coils] Poll address 12384 - 48 bits
2024-05-08 18:04:49.346 - [34mdebug[39m: modbus.1 (5752) [DevID_1/coils] Poll address 12480 - 48 bits
2024-05-08 18:04:49.347 - [34mdebug[39m: modbus.1 (5752) [DevID_1/coils] Poll address 12560 - 16 bits
2024-05-08 18:04:49.348 - [34mdebug[39m: modbus.1 (5752) [DevID_1/coils] Poll address 12608 - 48 bits

12288 + 16 = 12304
12304 + 16 = 12320
12320 + 64 = 12384
12384 + 48 = 12432
     (12432 - 12479 ???) 12432 - 12435 sind die Adressen, die mir momentan Probleme machen
12480 + 48 = 12528
     (12528 - 12559 ???)
12560 +16 = 12576
     (12576 - 12607 ???)
12608 + 48 = 12656

not align the addresses to 16 bits is checked
12288 + 2 = 12290
12306 + 8 = 12314
12335 + 49 = 12384
12399 + 37 = 12436
12480 + 37 = 12517
12560 + 16 = 12576
12608 + 33 = 12641

**Versions:**  
 - Adapter version: 6.1.0
 - JS-Controller version: 5.0.19
 - Node version: 18.19.1
 - Operating system: W10

**Additional context**  
https://forum.iobroker.net/topic/74542/modbus-fehlermeldung-unklar/11

[addresslist.txt](https://github.com/ioBroker/ioBroker.modbus/files/15257759/addresslist.txt)

these changes beginning at line 739 in Main.js could solve the problem:

        if (config.length) {
            result.length = result.addressHigh - result.addressLow;
            if (isBools && !localOptions.doNotRoundAddressToWord) {
                let oldstart = result.addressLow;
                result.addressLow = (result.addressLow >> 4) << 4;
                result.length += (oldstart - result.addressLow); 

                if (result.length % 16) {
                    result.length = ((result.length >> 4) + 1) << 4;
                }
                if (result.blocks) {
                    for (let b = 0; b < result.blocks.length; b++) {
                        let oldstart = result.blocks[b].start;
                        result.blocks[b].start = (result.blocks[b].start >> 4) << 4;
                        result.blocks[b].count += (oldstart - result.blocks[b].count);

                        if (result.blocks[b].count % 16) {
                            result.blocks[b].count = ((result.blocks[b].count >> 4) + 1) << 4;
                        }
                    }
                }
            }
        } else {
            result.length = 0;
        }

**Comment by Apollon77** [comment]
Thank you, it is in next version!
