### ISSUE TITLE
Adapter since 6.2.3 stops working because of floating values from Wago PLC

### ISSUE THREAD

**Issue by tomrey1** [ioBroker/ioBroker.modbus#513]
**Describe the bug**  
see title, solutions:
Eighther install stable or mark "not align"
s.a.:
https://forum.iobroker.net/topic/74542/modbus-fehlermeldung-unklar/23?_=1716963907631

**To Reproduce**  
2. Click on '...'
Install 6.2.3
**Expected behavior**  
Adapter working
**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>
6.2.3
21.7.3.1
12.22.12~dfsg-1~deb11u4
Debian 11
**Additional context**

**Comment by Apollon77** [comment]
@Q7Jensen any idea? Seems to be related to your change?

**Comment by Apollon77** [comment]
@tomrey1 please add a debug log

**Comment by tomrey1** [comment]
The error was:
[1] Poll error count: 7 code: {"errorCode":130,"exceptionCode":2,"message":"ILLEGAL DATA ADDRESS"}

**Comment by Q7Jensen** [comment]
@Apollon not at the moment, I have to understand the problem.

**Comment by micbuh** [comment]
i can confirm the issue. Same error msg. If time allows, I may dig deeper... 6.2.1 is working

**Comment by GermanBluefox** [comment]
Duplicate: https://github.com/ioBroker/ioBroker.modbus/issues/539
