### ISSUE TITLE
Two RPI Adapter as  ModbusMaster

### ISSUE THREAD

**Issue by Syil237** [ioBroker/ioBroker.modbus#515]
I have two RPIs in the network and an energy meter Siemens PAC3200. When I access the energy meter with one of them, I can read the meter. When I then activate the second adapter, the first one can read but the second one cannot. It doesn't matter which one is activated first. Both adapters are set as Master and on TCP.
![Modbusadapter_RPI_2](https://github.com/ioBroker/ioBroker.modbus/assets/46608768/2e0ebc7b-6fa5-4bd6-a97d-2b98053daca7)
![ModbusadapterRPI_1](https://github.com/ioBroker/ioBroker.modbus/assets/46608768/0c222923-f836-4130-80cc-16aaaf416044)

I want to be able to access the energy meter with both RPIs simultaneously.

**Comment by Apollon77** [comment]
What does the log say of the instance that do not work? Is the energy meter Siemens PAC3200 capable to handle two concurrent TCP connections?

**Comment by sakasitadi** [comment]
ok, its solved. 
![Screenshot 2024-06-03 210449](https://github.com/ioBroker/ioBroker.modbus/assets/154471408/c31bba11-35e6-4ff2-938e-f095233ea198)

**Comment by Apollon77** [comment]
So the device was only supporting one connection?
