### ISSUE TITLE
Problem reading coils

### ISSUE THREAD

**Issue by Maverick78de** [ioBroker/ioBroker.modbus#55]
I have trouble to read coils from a Phoenix Contact EV charge controller.
The adapter tries to read 16bit at once, which seem not to be possible at this controller. If I try to read only 8 bit everything is fine. 

How can I change the number of bits read by this adapter at once?

![image](https://user-images.githubusercontent.com/19900958/71644963-4d9ad080-2cd1-11ea-9169-b6759d24974e.png)
![image](https://user-images.githubusercontent.com/19900958/71644981-699e7200-2cd1-11ea-9ccd-b36058108f58.png)

Reading only 8 bit at once, everything is fine.

![image](https://user-images.githubusercontent.com/19900958/71645008-b2562b00-2cd1-11ea-82b2-586b00f4fb55.png)

I tried v2.0.9 and 3.0.0

**Comment by GermanBluefox** [comment]
Set "Max read request length (booleans)" to 8
