### ISSUE TITLE
CRC error

### ISSUE THREAD

**Issue by AlexCo88** [ioBroker/ioBroker.modbus#56]
Periodically there is a problem with CRC. An error appears in the log, and data reading through Modbus RTU fades. Correct work does not last long, from 1 to 3 hours. But when reading data using modpool there was no error.
This problem also occurred a year ago, but then I refused to use modbus rtu.

http://prntscr.com/qim7ss

Help solve the problem.

**Comment by GermanBluefox** [comment]
Hm. If your device sends invalid frame how can ioBroker adapter fix that?
