### ISSUE TITLE
scheduled restart of the adapter throws an error every time it's executed (error 156)

### ISSUE THREAD

**Issue by Percy2Live** [ioBroker/ioBroker.modbus#65]
I'm using an SMA inverter for solar panels with Modbus interface. I noticed that during a 24 - 48 hour cycle the connection randomly freezes so no new data are received by the adapter.

I fixed this issue for me by using the scheduled restart feature for this adapter (set up via iobroker web-interface).

Now the connection is stable, in case it freezes the adapter is restarted after 15 minutes latest.

Unfortunately every scheduled restart creates an error in the log file:

error | instance system.adapter.modbus.0 terminated with code 156 (156)

It would be great if there would be an option to deactivate the log levels for this adapter. During a day there are several entries of this kind in the log (1 for every scheduled restart).

**Comment by Apollon77** [comment]
That a scheduled restart logs an error is a topic for js-controller and is fixed in the coming js-controller 3.0 (should come to latest repository within the next week I expect). So I close here
