### ISSUE TITLE
Seit Update auf 3.0.2 keine Verbindung mit SMA Tripower Wechselrichter

### ISSUE THREAD

**Issue by TJJochen** [ioBroker/ioBroker.modbus#69]
Nach dem Update bleiben alle Modbus Instanzen auf gelb. 
Aktuelle Version 3.0.2
ioBroker 4.1.1
Node.js 12.17.0
JS Controller 3.1.4
NPM 6.14.4

**Comment by itProfi** [comment]
Same problem! After update not work!

**Comment by Apollon77** [comment]
Could you please share some logs? Pot. enable debug log?

**Comment by Apollon77** [comment]
But yes, verified!

**Comment by GermanBluefox** [comment]
Only one line was modified from 3.0.1 to 3.0.2.... it cannot be because of change

**Comment by Apollon77** [comment]
3.0.1 was never released!! So it is between 3.0.0 and 3.0.2!

**Comment by TJJochen** [comment]
Now i'm back on version 3.0.0 in ioBroker and it's work perfectly. I don't know, what's the problem of 3.0.2 is

**Comment by ingiz71** [comment]
Same behavior for me. After Upgrade to 3.0.2 both Modbus TCP instances (one master one slave) stay yellow. For me it look like that version 3.0.2 does only work if serial is available even if I use onle MODBUS TCP. At least after each resart of a 3.0.2 instance I get the following Message in the log: "Serial is not available". I downgraded to 3.0.0 and everything works now again. Except this the adapter works perfectly! :-)

**Comment by BigBadUlf** [comment]
Same behavior for me. Version 3.0.2 does not work. The adapter stays yellow. I can‘t connect to E3/DC Storage. Downgrade to version 3.0.0 brings back the full funtionality.
In my log is: „Serial is not available“. This message was in both logs. Maybe in Version 3.0.2 this is a problem.

**Comment by BigBadUlf** [comment]
Maybe the change from Blackbird77 in Version 3.0.1 produce the problem.

(BlackBird77) Fixes for Serial Timeouts done

**Comment by Garfonso** [comment]
Yes, sadly TCP does not work currently.
This is the log output:
```
2020-06-04 00:57:05.220  - info: host.Server instance system.adapter.modbus.0 started with pid 28667
2020-06-04 00:57:05.450  - info: modbus.0 (28667) starting. Version 3.0.2 in /opt/iobroker/node_modules/iobroker.modbus, node: v12.16.3, js-controller: 3.1.4
2020-06-04 00:57:05.461  - warn: modbus.0 (28667) Serial is not available
```

**Comment by smartboart** [comment]
Not only tcp...

**Comment by Anzic23** [comment]
if you need statistics, then it doesn’t work for me either. TCP connection.

**Comment by Matzebhv** [comment]
Same Problem here with serial connection to our Growatt PV-Inverter. Switching back to 3.0.0 fixes this issue. Even in silly nothing wrong in log.

**Comment by BigBadUlf** [comment]
Version 3.0.3 works fine.
The modbus objects are updatet.

Here my log:
modbus.0 | 2020-06-05 09:42:40.846 | info | (4403) Connected to slave 192.168.178.86
-- | -- | -- | --
modbus.0 | 2020-06-05 09:42:39.822 | warn | (4403) Serial is not available
modbus.0 | 2020-06-05 09:42:39.622 | info | (4403) starting. Version 3.0.3 in /opt/iobroker/node_modules/iobroker.modbus, node: v12.16.3, js-controller: 3.1.4

Thx @GermanBluefox
