### ISSUE TITLE
Can't select serial port.  The pull down menu only shows undefined.  /dev/ttyUSB0 seems to be working and available.

### ISSUE THREAD

**Issue by kskenyon** [ioBroker/ioBroker.modbus#75]
This on a docker container with docker-compose.

version: '2'

services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    environment:
      - TZ=America/Eastern
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - USBDEVICES=/dev/ttyUSB0
    expose:
      - "8081"
      - "8082"
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8087:8087"
      - "8088:8088"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - iobrokerdata:/opt/iobroker
volumes:
     iobrokerdata:
docker-compose.yml (END)

**Describe the bug**  
Can't select serial port.  The pull down menu only shows undefined.  /dev/ttyUSB0 seems to be working and available.
**To Reproduce**  
1. Go to '.modbus adapter general configuration page.'
2. Click on '.port..'
3. Scroll down to '...Only Undefined is shown, should show /dev/ttyUSB0.'

**Expected behavior**  
should show /dev/ttyUSB0.'
**Screenshots & Logfiles**  

modbus.0 | 2020-09-20 00:18:54.165 | warn | (2061) On error: {}
-- | -- | -- | --
modbus.0 | 2020-09-20 04:17:54.163 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:17:53.162 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:17:20.397 | info | (2061) List of port: [{"comName":"/dev/ttyUSB0"}]
modbus.0 | 2020-09-20 04:16:53.160 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:16:52.157 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:15:52.156 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:15:51.155 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:14:51.153 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:14:50.152 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:13:50.150 | warn | (2061) On error: {}
modbus.0 | 2020-09-20 04:13:49.149 | warn | (2061) On error: {}

**Versions:**  
 - Adapter version: <adapter-version>3.1.9
 - JS-Controller version: <js-controller-version> 3.1.4
 - Node version: <node-version> 12.16.3
 - Operating system: <os-name>Raspbian Stretch

**Additional context**  
Serialport is installed.

**Comment by cyberax17** [comment]
Dear All, any solution to this bug? Ran into it all of a sudden today. No change except restart of the adapter.

**Comment by Lichte12** [comment]
Have you tried to delete the adpater and reinstall? This fixed this problem for me recently.

**Comment by cyberax17** [comment]
Will this delete all my register assignments? How would I preserve those?

**Comment by Lichte12** [comment]
Export all register to CSV first. After reinstall import again.
![snip](https://user-images.githubusercontent.com/48066530/100758903-52d83200-33f0-11eb-9f34-4584f0ff505d.JPG)

**Comment by cyberax17** [comment]
Just deleted and re-installed the modes adapter. no effect unfortunately. same issue: ports are all "undefined" .

**Comment by kskenyon** [comment]
I did the same thing. No change.

**Comment by cyberax17** [comment]
I now use mbusd  as a TCP/MODBUS bridge and this seems to work fine.

**Comment by Apollon77** [comment]
I think I have an idea ... let me check something

**Comment by Apollon77** [comment]
Please try 3.1.11

**Comment by cyberax17** [comment]
thanks for the quick update, unfortunately it did not do the job. same issue. Do I need to do something else?

**Comment by Apollon77** [comment]
Please try to "iobroker upload modbus" ... really not working?

**Comment by Apollon77** [comment]
hm ... I see ... i check again tonight

**Comment by Apollon77** [comment]
check Github version please ... or wait for 3.1.12 in latest soon

**Comment by kskenyon** [comment]
I still don’t seem to be able to connect.  Serial Port not available even after a reset.  Works OK from a node-red modbus node so hardware is OK.

Kevin


2020-12-06 02:30:50.913	info	(30859) Disconnected from slave
modbus.0	2020-12-06 02:30:50.911	info	(30859) Connected to slave
modbus.0	2020-12-06 02:30:50.490	info	(30859) starting. Version 3.1.12 in /opt/iobroker/node_modules/iobroker.modbus, node: v10.21.0, js-controller: 3.1.6
modbus.0	2020-12-06 02:30:47.172	info	(30837) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
modbus.0	2020-12-06 02:30:47.169	info	(30837) terminating
modbus.0	2020-12-06 02:30:47.163	info	(30837) Got terminate signal TERMINATE_YOURSELF
modbus.0	2020-12-06 02:30:39.741	info	(30837) List of port: [{"path":"/dev/ttyUSB0"}]
modbus.0	2020-12-06 02:30:39.741	info	(30837) Check /dev/ttyUSB0 : false
modbus.0	2020-12-06 02:30:39.739	info	(30837) Verify []
modbus.0	2020-12-06 02:30:19.928	info	(30837) Disconnected from slave
modbus.0	2020-12-06 02:30:19.927	info	(30837) Connected to slave
modbus.0	2020-12-06 02:29:19.922	info	(30837) Disconnected from slave
modbus.0	2020-12-06 02:29:19.920	info	(30837) Connected to slave
modbus.0	2020-12-06 02:29:19.099	info	(30837) starting. Version 3.1.12 in /opt/iobroker/node_modules/iobroker.modbus, node: v10.21.0, js-controller: 3.1.6
modbus.0	2020-12-06 02:29:14.242	info	(30816) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
modbus.0	2020-12-06 02:29:14.240	info	(30816) terminating
modbus.0	2020-12-06 02:29:14.238	info	(30816) Got terminate signal TERMINATE_YOURSELF
modbus.0	2020-12-06 02:28:52.584	info	(30816) Disconnected from slave
modbus.0	2020-12-06 02:28:52.583	info	(30816) Connected to slave
modbus.0	2020-12-06 02:27:52.579	info	(30816) Disconnected from slave
modbus.0	2020-12-06 02:27:52.576	info	(30816) Connected to slave
modbus.0	2020-12-06 02:27:52.075	info	(30816) starting. Version 3.1.12 in /opt/iobroker/node_modules/iobroker.modbus, node: v10.21.0, js-controller: 3.1.6
modbus.0	2020-12-06 02:27:48.858	info	(30352) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
modbus.0	2020-12-06 02:27:48.851	info	(30352) terminating
modbus.0	2020-12-06 02:27:48.846	info	(30352) Got terminate signal TERMINATE_YOURSELF
modbus.0	2020-12-06 02:27:35.445	info	(30352) List of port: [{"path":"/dev/ttyUSB0"}]
modbus.0	2020-12-06 02:27:35.445	info	(30352) Check /dev/ttyUSB0 : false
modbus.0	2020-12-06 02:27:35.442	info	(30352) Verify []
modbus.0	2020-12-06 02:26:51.935	info	(30352) Disconnected from slave
modbus.0	2020-12-06 02:26:51.934	info	(30352) Connected to slave
modbus.0	2020-12-06 02:25:51.928	info	(30352) Disconnected from slave
modbus.0	2020-12-06 02:25:51.927	info	(30352) Connected to slave

**Comment by Apollon77** [comment]
Ok, so : In admin now all is ok and you can choose the port, but now connection does not work?

Please first run "Iobroker fix" to make sure all needed permissions are correct.

If still not work please disable the adapter in admin, open a shell and run "iobroker debug modbus.0". Post output here

**Comment by SSonder0815** [comment]
I had the same issue with missing port descriptions that lead to an error executing the modbus adapter in serial mode, it worked for me to update the linux os on the raspberry, restart the iobroker and voila, iobroker connected to the Modbus RTU server.

**Comment by ViPtAd** [comment]
Hi all,

i am experience the same issue with nearly the same configuration; installed iobroker docker from buanet repo, created the device connection as shown below:

![image](https://user-images.githubusercontent.com/100418019/155713163-ea131d84-327e-4f72-8924-8d2b935861cf.png)
![image](https://user-images.githubusercontent.com/100418019/155713206-65ceabad-1e76-45fd-b21d-c653865e67c0.png)
(ok, it is used in portainer but this should not be the deal...)

I checked the devices in the console (e voila):
```
root@iobroker:/opt/iobroker# ls -al /dev/serial/by-id/*
crw-rw---- 1 root dialout 188, 0 Feb 25 13:02 /dev/serial/by-id/rs485port1
crw-rw---- 1 root dialout 188, 1 Feb 25 13:02 /dev/serial/by-id/rs485port2
```

But the selection is empty:
![image](https://user-images.githubusercontent.com/100418019/155713063-d6a02383-fd80-4549-85a7-8e68a170ece7.png)

best regards and thank you for your help!

**Comment by ViPtAd** [comment]
OK, solved the problem for me:
I wanted to give it a try if I change the alias, now the adapters are showing up:
![image](https://user-images.githubusercontent.com/100418019/155714260-c484b0de-f314-43cf-ae1e-aa07f246f015.png)
