### ISSUE TITLE
Processing sequence of OFFSET and FACTOR reversible?

### ISSUE THREAD

**Issue by cyberax17** [ioBroker/ioBroker.modbus#80]
My modbus slave delivers values in a format so that you have to calculate:
(VALUE - 1000) / 10 to get the actual value.
I thought the OFFSET and FACTOR parameters would be good to do this but I realize they act in a reverse sequence, thus first  multiply with factor and then add/substract offset.

Is there any way to reverse this calculation sequence or any other idea so solve without script?

Many thanks for your help!
Cheers

**Comment by nkleber78** [comment]
A possible solution would having a formula field in addition. If the standard calculation does not fit, just adding a formula. This would then also allow some dynamic scaling based on read values. E.g. for Values where the device also transfers a scaling factor which is not stable during runtime.
