### ISSUE TITLE
Modbus adapter wird in Admin nicht korrekt angezeigt

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.modbus#83]
Im Admin wird der modbus Adapter nicht korrekt angezeigt. Es scheint dass irgendwo eine Kleinigkeit im Code nicht passt sodass z.b. löschen von Instanzen usw. je nach Ansicht nicht oder nicht sauber dargestellt wird. Siehe screenshots
<img width="291" alt="Screenshot 2020-12-12 at 21 51 24" src="https://user-images.githubusercontent.com/35381530/101994685-763e8f00-3cc4-11eb-8208-e59bbbc6c023.png">
<img width="1228" alt="Screenshot 2020-12-12 at 21 50 41" src="https://user-images.githubusercontent.com/35381530/101994687-7b9bd980-3cc4-11eb-9c96-be62d70a4907.png">

**Comment by GermanBluefox** [comment]
Ich kann nicht reproduzieren

**Comment by nkleber78** [comment]
Hallo @GermanBluefox 
Ich habe die Ursache gefunden. Das problem war dass bei system.adapter.modbus.upload 1% drin war. Dies führt dann dazu dass es nicht korrekt angezeigt wird. Ich vermute der Zahlenwert habe ich versehentlich dort eingetragen... Vielleicht kann sich ja jemand dieses Thema im Admin anschauen. Denn es ist reproduzierbar für jeden Adapter...
