### ISSUE TITLE
Clear name of instances

### ISSUE THREAD

**Issue by Tagiwara** [ioBroker/ioBroker.modbus#86]
In the meantime I have 5 instances of the adapter and find it a bit confusing in the tree object.

would it be possible in a later version to give the individual instances a clear name?

Example: modbus.0 = inverter, modbus.1 = wallbox, modbus.2 = heat pump, etc.

**Comment by Apollon77** [comment]
Yes this is a more generic problem. it seems there is no basic object created (modbus.X) and so you can not set a name on it ... need to think about that

**Comment by Apollon77** [comment]
Please install github version (version number will be the same) ... after restart of adapter you should be able to set a name, please also check if the name persists on next restart
