### ISSUE TITLE
Square brackets are not allowed in register name

### ISSUE THREAD

**Issue by Andr3asB** [ioBroker/ioBroker.modbus#87]
Description: When users create (input) registers and add a pair of square brackets , e.g. [Watt] or [m/s], then the register is ignored until the square brackets are removed from the name. 

Tested and confirmed behaviour in versions 3.1.10 and 3.2.3.

Experienced behaviour: 
The register becomes invisible in the list of objects.

Expected behaviour:
a, There should be a warning message to users, that this value causes
b, no matter of square brackets the register should be operated as all other registeres are.

**Comment by matthias882** [comment]
Confirmed for 3.2.4 too.
There ist no note in manual and no error or warning in the log.
I tried some hours before i found the solution in this issue.

Some register names of the power-meter "Janitza UMG96-RM-E" in their manual are with Brackets, for example
11523 | float | _MONTHLY_VWH[0]
11525 | float | _MONTHLY_VWH[1]
I tried to use the original names with no success.
