### ISSUE TITLE
Modbus Adapter verliert sporadisch Verbindung zu SMA Tripower WR

### ISSUE THREAD

**Issue by TJJochen** [ioBroker/ioBroker.modbus#92]
Hallo in die Runde...

Seit ca. einem Dreiviertel Jahr beobachte ich, dass der Modbus Adapter die Verbindung zu meinen SMA Wechselrichter verliert.
Ich habe 2 Tripower. Mal verliert er den einen, mal den anderen und hin und wieder auch beide gleichzeitig. Dann wird das Logfile mit nachfolgenden Meldungen minütlich geflutet:
![image](https://user-images.githubusercontent.com/35068587/106781463-6189d200-6649-11eb-933f-d9f5407665c1.png)
Ein Neustart des Adapters hilft hier nicht weiter. Einzig die Spannungsfreischaltung DC und AC seitig des WR bringt hier für Stunden oder Tage Abhilfe, bis das Problem wieder auftaucht. Kann das jemand so bei sich auch beobachten?
Da die Häufigkeit zunimmt, jetzt die Meldung hier auf Github.

Modbus Adapter 3.2.4
ioBroker 4.2.1
JS-Controller 3.2.13
Node-JS 14.5.4
NPM 6.14.10
OS Debian 10

Danke für Hilfe :-)
Gruß Jochen

**Comment by Apollon77** [comment]
Hm ... also wenn ein Adapter Neustart nicht hilft und nur Stromlos machen des gegengeräts, dann liegt der Fehler dort. Der adapter versucht nur sich neu zu verbinden und bekommt ständig einen Timeout. Was soll der Adapter sonst tun?
