### ISSUE TITLE
Add the ability to export-import settings

### ISSUE THREAD

**Issue by Andrey2509** [ioBroker/ioBroker.modbus#99]
Please add the ability to export-import settings (register settings), it is required to transfer a large number of records between different installations and instances.

**Comment by Apollon77** [comment]
CSV export/importis already there in the admin ui ... check "top right" over the table

**Comment by Apollon77** [comment]
Also the whole instance settings can be saved via admin and reimported (on other plave in admin). Or what do you miss?
